### ISSUE TITLE
PVText display issue for scientific notation

### ISSUE THREAD

**Issue by plasmapug** [pyepics/pyepics#11]
So first, I'm Peter, I'm at the ANU in Canberra working with the EPICS system developed by Angus Gratton.  Software Developer is not my primary role, so please be patient with me!

On to the issue.  If I use a PVText on a EPICS record with a defined precision, say 3, and that number is 1e-5 or smaller, then the resulting text is 1e-5 (or similar).  This is fine.  However, if that number is 1e-4, then the python conversion to string results in 0.0001.  If the EPICS record precision is set to 3, then the PVText is 0.000, dropping the one.  We don't want that.

We are basically tracking beam currents and I've set the precision to 3 so that normal range nanoamp currents come up at e.g. 2.34e-9 (as per user request).  However, at the source, they occasionally get to >100e-6.  This then shows up as 0.000 A.

I'm still learning about overriding methods in python, still can't figure out how to override _pvEvent which is where the formatting occurs (as far as I can tell).

Cheers
Peter

**Comment by klauer** [comment]
@plasmapug, since this issue is almost 6 years old at this point, I'm closing it. If you still need this functionality, please comment and it can be reopened.
