### ISSUE TITLE
PV status value in the value changed callback

### ISSUE THREAD

**Issue by hinxx** [pyepics/pyepics#140]
I'm little confused what kind of status value should I expect in the value changed callback? Are the possible values `ECA_xxx` from `epics-base/src/ca/client/caerr.h`?

Up to now I error message output on `kw['status'] != 0`, but I started getting `kw['status'] == 6` for one of the PV on my network.
I can access PVs with CLI `caget` no matter what the pyepics status says, with no issues.
I'm not sure how to deal with the PVs that appear to be normally accessible, but pyepics status is not 0.

This is part of the callback code:
```
    def _onValueChange(self, pvname=None, value=None, char_value=None, **kw):
        """ PV data monitor callback.

        Assemble the update data response and hand it over to
        update callback for distibution to the clients.
        """
        if kw['status'] != 0:
            log.error('%s : status is not 0!!' % (pvname))
            return

...
```

Should I use PV.get_timevars() from within callback to obtain 'status'?

**Comment by newville** [comment]
@hinxx   Sorry for the trouble.  I don't think I've ever seen that status code before.  From a basic `grep ECA_ base/src/ca/client/caerr.h`, it looks like status=6 is

    #define ECA_NORMAL          DEFMSG(CA_K_SUCCESS,    0) /* success */
    #define ECA_MAXIOC          DEFMSG(CA_K_ERROR,      1) /* defunct */ 
    #define ECA_UKNHOST         DEFMSG(CA_K_ERROR,      2) /* defunct */
    #define ECA_UKNSERV         DEFMSG(CA_K_ERROR,      3) /* defunct */
    #define ECA_SOCK            DEFMSG(CA_K_ERROR,      4) /* defunct */
    #define ECA_CONN            DEFMSG(CA_K_WARNING,    5) /* defunct */
    #define ECA_ALLOCMEM        DEFMSG(CA_K_WARNING,    6) 
    ....

which makes it look like a memory allocation *warning*.   I would guess that means "on the CA server", but I don't know for sure.  

It looks like some of the other status codes are also warnings, not rerrors.   Maybe it's not quite "bulletproof" to bail-out on any non-zero status?  

The command-line `caget` is definitely taking a different path through the CA library.  It does a "search and connect", and then a real "get()" without setting up monitors. That might act differently, and it might ignore status values that are warnings.

**Comment by hinxx** [comment]
Thanks for confirming the source of status codes! The CA manual also says that handling CA status is not simple as in Unix world where 0 is OK, all other values NOT OK.

> It looks like some of the other status codes are also warnings, not rerrors. Maybe it's not quite "bulletproof" to bail-out on any non-zero status?

I will probably (selectively?) ignore warnings, and bail out on errors only (looking at the caerr.h).

**Comment by newville** [comment]
@klauer Thanks Ken -  you are right.   I was completely off.  Like you say, if the status in the event handler structure is not ECA_NORMAL, the user-level callback is not even called (maybe something should be done on that condition?).     

The `status` that will make it to the python callback is the "alarm status" from the STS structure.  I'm not sure what some of those values mean, or what a user-level callback should do if the status is not "NO_ALARM".   I guess it should log to an alarm handler and/or send email to someone who knows what to do!

**Comment by ralphlange** [comment]
When connecting to EPICS databases, this is the enumeration used in the STAT field of EPICS records, giving a "reason" type information.
The STS structure retrieved by CA contains status and severity; an application would need both to get the full picture.

**Comment by klauer** [comment]
@newville Right - it really depends on what the end goal of your application is. A user-facing GUI, for example, might show a different border around a widget depending on the alarm status/severity.

@hinxx Alarm status is just an enum in epics-base: https://github.com/epics-base/epics-base/blob/7.0/modules/libcom/src/misc/alarm.h without much in the way of additional information.
I think reading through the alarm section in the [RRM](https://webcache.googleusercontent.com/search?q=cache:xD5CFuheLj0J:https://wiki-ext.aps.anl.gov/epics/index.php/RRM_3-14_Concepts+&cd=1&hl=en&ct=clnk&gl=us#Alarm_Specification) would be useful for you to get some more background on what these mean. (side note: linked the google cache page as Argonne apparently has some https certificate related issues)

**Comment by hinxx** [comment]
Thanks guys, now I have a better picture on what is what!
