### ISSUE TITLE
PV retrieval via caget() vs PVObject

### ISSUE THREAD

**Issue by vstadnytskyi** [pyepics/pyepics#167]
A Process Varible(PV) can be obtained in few different ways. One way would be to use `epics.caget` function and another one via `PVObject`. 
snippet of the commands in ipython
```
In [8]: epics.caget('NIH:OPTICAL_SCATTERING.MEAN')
Out[8]: array([], dtype=float64)
In [18]: epics.caget('NIH:OPTICAL_SCATTERING.MEAN', as_string = True)
Out[18]: '[]'
In [9]: mean_value = epics.PV('NIH:OPTICAL_SCATTERING.MEAN')
In [10]: mean_value.value
Out[10]: 286.04
```

The documentation for the `caget` suggests it should work. However, two different methods behave differently.

```
def caget(pvname, as_string=False, count=None, as_numpy=True,
          use_monitor=False, timeout=5.0):
    """caget(pvname, as_string=False,count=None,as_numpy=True,
             use_monitor=False,timeout=5.0)
    simple get of a pv's value..
       >>> x = caget('xx.VAL')

    to get the character string representation (formatted double,
    enum string, etc):
       >>> x = caget('xx.VAL', as_string=True)

    to get a truncated amount of data from an array, you can specify
    the count with
       >>> x = caget('MyArray.VAL', count=1000)
    """
```

**Comment by vstadnytskyi** [comment]
Is it possible it is related to the error below?

**** The executable "caRepeater" couldn't be located
**** because of errno = "No such file or directory".
**** You may need to modify your PATH environment variable.
**** Unable to start "CA Repeater" process.

**Comment by newville** [comment]
@vstadnytskyi That's weird.   To be clear, `caget()` really is a thin wrapper around `PV()`.

I think it might have something to do with the data type and contents of the PV.   What does `epics.cainfo()` report for that PV?  At first it looks like it is an empty waveform, and then it looks like a regular float.  Is it meant to hold a variable-length array?   And did the value actually change between those two calls?

The carepeater program is a useful utility for optimizing some communications, but everything should work OK without it.

**Comment by vstadnytskyi** [comment]
@newville The epics.cainfo returns an empty array in the 'value'.

it looks like an empty array if I get via caget and it is a number if I use the PVObject. The PV posted by the server was always a float number and hasn't change.

```
epics.cainfo('NIH:OPTICAL_SCATTERING.MEAN')
== NIH:OPTICAL_SCATTERING.MEAN  (time_double) ==
   value      = array  []
   char_value = '[]'
   count      = 0
   nelm       = 1
   type       = time_double
   units      =
   precision  = 8
   host       = nih-instrumentation.cars.aps.anl.gov:5069
   access     = read/write
   status     = 0
   severity   = 1
   timestamp  = 1559513225.766 (2019-06-02 17:07:05.76600)
   posixseconds        = 1559513225.0
   nanoseconds= 766000032
   upper_ctrl_limit    = 0.0
   lower_ctrl_limit    = 0.0
   upper_disp_limit    = 0.0
   lower_disp_limit    = 0.0
   upper_alarm_limit   = 0.0
   lower_alarm_limit   = 0.0
   upper_warning_limit = 0.0
   lower_warning_limit = 0.0
   PV is internally monitored, with 0 user-defined callbacks:
=============================
```

**Comment by newville** [comment]
@vstadnytskyi  That "count=0, nelm=1" looks odd to me, and may very well be the problem....  I'm not sure how one gets that.   Do you know how / where the PV is defined and/or what kind of record it is?

**Comment by vstadnytskyi** [comment]
@newville The PV was defined on a server I wrote using this [library](https://github.com/friedrich-schotte/Lauecollect/blob/master/CAServer.py). The library was written by Friedrich Schotte and there is a convenient way to interact with PVs(via functions `casget('NAME.VAR'), casput('NAME.VAR',1.0) and casmonitor('NAME.VAR', callback = callback_function`). I don't know what kind of record it is. I assumed that all communication (CAServer and CA Client implementation by Friedrich) is taken care of under the hood and I can focus on a higher level programming. I will check with Friedrich and report here later. Even though he used channel access 2 documentation, there might be some incompatibilities.

**Comment by vstadnytskyi** [comment]
It seems that the Channel access in PyEPICS 3.3.3 (bundled with EPICS Version 3.16) does not specify an element count when requesting a PV, whereas in version 3.14 the element count is specified as 1 when requesting a scalar PV. However, the older version of PyEPICS 3.2.4 (EPICS 3.14) did. Our implementation of CAServer works with PyEPICS 3.2.4 but not with PyEPICS 3.3.3. 

CA 3.14 uses the DATA_COUNT field in the reply to the CREATE_CHANNEL command as DATA_COUNT parameter for the next READ_NOTIFY or EVENT_ADD request. CA 3.16 ignores the DATA_COUNT field in the reply to the CREATE_CHANNEL command, and zeros out the DATA_COUNT field of the next READ_NOTIFY or EVENT_ADD request.

**Comment by klauer** [comment]
Think #139 might be related?

**Comment by newville** [comment]
@vstadnytskyi   A PV with nelm=1  implies a scalar value, not an array.  That is, "nelm" means maximum number of array elements and "count" means current number of valid elements (always from the front).  

What got fixed (yes, fixed!) in #139 was the case where nelm > 1 and count = 0 or 1.   Previously, we had used count=1 to decide whether the data was an array, and that is wrong.  It might be that there is currently only 1 valid element of the array but with nelm > 1, it is still an array.

But 'nelm=1, count=0' seems like a really odd situation.  Is this intended to be an array with up to one element, but currently empty?  

I would sort of guess that the home grown CA Server (fun! but definitely hard for us to support) might need to make sure that the count field is 1 for this PV.

**Comment by vstadnytskyi** [comment]
In principle, the homegrown CA Server should be compatible with the CA protocol. However, in this case, it wasn't. According to my colleague who wrote the core functionality, our server is compatible with EPICS 3.14. But there were changes made in the protocol in EPICS 3.16 which caused a problem. Or it could have been a bug, to begin with. I am not sure.  I am planning to write documentation so other people can benefit from it and help with finding bugs.

**Comment by newville** [comment]
I think we can close this...
