### ISSUE TITLE
Problem with formatting of PVText field to specified precision

### ISSUE THREAD

**Issue by vstadnytskyi** [pyepics/pyepics#180]
I ma having troubles with PVTextCtrl in epics.wx. I have created a simple GUI and I can see a value of the PV I am looking at, However, I don't get it formatted to specified precision.

I am creating a field with the code below. Works fine. except I have to specify minor_alarm color (bug reported in #166)
`epics.wx.PVText(self.panel, pv='TEMP.RBV',minor_alarm = wx.Colour(5, 6, 7),auto_units = True)
`
If Iook at the value of .PREC, I get 3. This should define the precision to 3 value after decimal point. However, it doesn't work. What am I doing wrong?

```
In [34]: temp = epics.PV("TEMP.RBV")
In [35]: temp.value
Out[35]: 7.636315346
In [36]: temp.precision
Out[36]: 8

In [37]: prec = epics.PV("TEMP.PREC")
In [38]: prec.value
Out[38]: 3
```
Note, precision of temperture is 8 but the actual value of .PREC is 3.

Here is a screenshot of the GUI with the field created in the way showen above. 
<img width="297" alt="image" src="https://user-images.githubusercontent.com/29989124/65534596-cd90ed80-decd-11e9-81de-18e32b1e8275.png">

**Comment by vstadnytskyi** [comment]
Also, Why do I get this error/warning?
```
**** The executable "caRepeater" couldn't be located
**** because of errno = "No such file or directory".
**** You may need to modify your PATH environment variable.
**** Unable to start "CA Repeater" process.
CA client library is unable to contact CA repeater after 50 tries.
Silence this message by starting a CA repeater daemon
or by calling ca_pend_event() and or ca_poll() more often.
```

**Comment by newville** [comment]
@vstadnytskyi  Hm, that seems sort of odd.  You may need to get the control fields to have the precision attribute with 

    temp = epics.PV("TEMP.RBV")
    temp.get_ctrlvars()

It *should* be that the correct precision is fetched when you do
 
    print(temp.precision)
 
But, I don't know why that would disagree with the `.PREC` field unless the record was messed up to not be correctly setting the precision of the `.RBV` field.    I can imagine that could happen with PVs set up by some faulty CAS.   You might check with

    epics.cainfo('TEMP.RBV')


For the `caReapeter not located` messages: this means `caReapeter` is not in your PATH.  It's usually not a problem, and only gives a flurry of not-very-serious warning messages.

**Comment by vstadnytskyi** [comment]
Is it because .PREC has incompatible type? Also, the units field is empty, but the '.EGU' is not. This issue might be related to #167. We have figured out that the problem on #167 was due to bugs in the home developed CAServer implementation.

@newville Thanks a lot for your quick replies. I learn a lot and you always give useful advice how to procede with my problems. 

```
pics.cainfo('TEMP.RBV')
== TEMP.RBV  (time_double) ==
   value      = 7.61659
   char_value = '7.61658764'
   count      = 1
   nelm       = 1
   type       = time_double
   units      = 
   precision  = 8
...
```
```
epics.cainfo('TEMP.PREC')                                                                                                                    
== TEMP.PREC  (time_long) ==
   value      = 3
   char_value = '3'
   count      = 1
   nelm       = 1
   type       = time_long                       <------
   units      =                                 <------
...
```
```
In [4]: epics.cainfo('TEMP.EGU')
== TEMP.EGU  (time_string) ==
   value      = C
   char_value = 'C'
   count      = 1
   nelm       = 1
   type       = time_string
...
```

**Comment by newville** [comment]
@vstadnytskyi  Hm, and again: that seems sort of odd.  Are you using some non-standard CA server?   Because, that is just not enough components for a CTRL variant of a PV.    That is: what makes you think that the "TEMP.PREC" PV should be related to the precision of "TEMP.RBV".  Are they derived from the same record or did you just make up two PVs with names "TEMP.RBV" and "TEMP.PREC"?

I doubt this is related to "incompatible types" or really to Python.   What does the command-line tool `caget` give for

    caget -d 30 TEMP.RBV

that will also report the precision.  I'll bet it reports the same as pyepics.

**Comment by vstadnytskyi** [comment]
@newville 
I have fixed my previous comment. I haven't included half of the output from cainfo. 

> @vstadnytskyi Hm, and again: that seems sort of odd. Are you using some non-standard CA server? Because, that is just not enough components for a CTRL variant of a PV. That is: what makes you think that the "TEMP.PREC" PV should be related to the precision of "TEMP.RBV". Are they derived from the same record or did you just make up two PVs with names "TEMP.RBV" and "TEMP.PREC"?
> 
> I doubt this is related to "incompatible types" or really to Python. What does the command-line tool `caget` give for
> 
> ```
> caget -d 30 TEMP.RBV
> ```
> 
> that will also report the precision. I'll bet it reports the same as pyepics.

I need to get EPICS on my computer first before I can use 'caget' in the terminal. I will report back when this will be done. 

Thank you!
