### ISSUE TITLE
epics.motor.get() does not work with alias, but epics.device.get() does

### ISSUE THREAD

**Issue by schlepuetz** [pyepics/pyepics#181]
Hi all, 

I noticed some inconstency between the `get()` methods of `epics.device` and `epics.motor` (which is subclassed from `epics.device`). `epics.motor.get()` does not return the value of a PV if the defined alias is specified instead of the actual PV suffix, while this seems to be working just fine for `epics.device.get()`.

This is not a big problem, and one can easily work around it by specifying the actual PV suffix, but it did create quite some confusion and lengthy error chasing on my end. 

Example:

    In [1]: from epics import device, motor
    In [2]: my_alias = {'drive': 'VAL'}
    In [3]: my_dev = device.Device(prefix="TEST_MOTOR", aliases=my_alias)
    In [4]: my_mot = motor.Motor(name="TEST_MOTOR")

    # The following works for the actual suffix, but not for the alias
    In [5]: my_mot.get('VAL')
    OUT [5]: 1880.59999      # This is the correct drive value
    In [6]: my_mot.get('drive') 
    OUT [6]:                         # Nothing is returned after a longer timeout

    # While for the device, both the suffix and alias return the desired result
    In [7]: my_dev.get('VAL') 
    OUT [7]: 1880.59999      # This is the correct drive value
    In [8]: my_dev.get('drive') 
    OUT [8]: 1880.59999      # This is the correct drive value

I'll be happy to help, but would like to make sure that this behaviour is not intended or necessary due to reasons I have failed so see so far.

Thanks a lot!
Christian

**Comment by newville** [comment]
@schlepuetz  Oh, that's a good point.   `Motor` has a lot of attribute /aliases already mapped, so that 
`my_mot.drive` will work, but this is not exactly compatible with the rest of `Device`. 

Probably the simplest thing to do would be to write an explicit `Motor.get()` that did accept its own aliases.  I'll do that and submit a PR.

**Comment by schlepuetz** [comment]
Great, thanks a lot @newville !
