### ISSUE TITLE
wx.BitmapButton : Additional wxPython Widgets for pyepics

### ISSUE THREAD

**Issue by vstadnytskyi** [pyepics/pyepics#192]
I have found myself in a need to create a Button with a bitmap instead of a text. I want to make nice buttons with arrows on them. See the image below. 
<img width="75" alt="image" src="https://user-images.githubusercontent.com/29989124/73406858-20841280-42bd-11ea-8712-fd2ce90959cd.png">

Would it be useful to have PVBitmapButton next to PVButton in pyepics?

**Comment by newville** [comment]
@vstadnytskyi  Sure, why not?   I have at least one app where I use custom arrows to move motors, but I guess I'm not using a PV mixin class for that.

**Comment by vstadnytskyi** [comment]
A pull-request was created and added to the master branch. So I think we can close this issue.
