### ISSUE TITLE
Error caused by a bug in PVEnumChoice

### ISSUE THREAD

**Issue by vstadnytskyi** [pyepics/pyepics#193]
I am getting the following error.

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wx/core.py", line 3259, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/Users/femto-13/All-Projects-on-femto/LaserLab/Software/pyepics/epics/wx/wxlib.py", line 819, in SetPV
    pv_value = pv.get(as_string=True)
AttributeError: 'str' object has no attribute 'get'
```
My code to create an PVEnumChoice object

`configuration_modes = epics.wx.PVEnumChoice(self.panel, pv = prefix + 'configuration_modes', choices = ['SAXS/WAXS','LAUE','Bogus'], size = (180,40))`

the post mortem examination has shown that variable "pv" is a string.

```
-> pv_value = pv.get(as_string=True)
(Pdb) pv
'NIH:BEAMLINE.configuration_modes'
```

I have traced it down to a typo in the SetPV method.

On the line 617 and below we check if pv variable is a string or PV object. it creates a pv object if it a string and assigns it to self.pv. If it is a pv object it assigns it to self.pv

https://github.com/pyepics/pyepics/blob/3af493d29852a0ac7dd43e7e39f1ccda353a3721/epics/wx/wxlib.py#L617

If supplied pv variable is a pv object code works fine. If it a string, the lines 632 issue an error.

https://github.com/pyepics/pyepics/blob/3af493d29852a0ac7dd43e7e39f1ccda353a3721/epics/wx/wxlib.py#L632

It is a simple fix. I can create pull-request if this is ok.
Old
```
pv_value = pv.get(as_string=True)
enum_strings = pv.enum_strs
```

New
```
pv_value = self.pv.get(as_string=True)
enum_strings = self.pv.enum_strs
```

**Comment by newville** [comment]
@vstadnytskyi  Right, those should be `self.pv.get(as_string=True)` and `self.pv.enum_strs`.   Apparently everywhere I use this, I use 

     x = PVEnumChoice(pvobject)

instead of 

    x  = PVEnumChoice(pvname)

But also: you do not supply `choices` to `PVEnumChoice`.  The idea for PVEnumChoice is to use the `enum_strs` already defined for that PV and to allow that to be set or to respond if that value changes because of some other action elsewhere on the network.   If you want to have a PV take one of a set of values, you don't need PVEnumChoice, just use a Choice and have the PV set to that value on the Choice event.

**Comment by vstadnytskyi** [comment]
See pull request that should fix the issue #194

**Comment by vstadnytskyi** [comment]
I have an enum list of string create in caproto. It looks like only 25 characters are getting transferred. Is there limitation how many characters i can have in the enum in channel access protocol, pyepics or caproto?

```
in [103]: from epics import PV
In [104]: p = PV("BEAMLINE:SERVER.choices")
In [105]: p.enum_strs
Out[105]:
('Insert',
 'Retract',
 ' ',
 '1111111111222222222233333',
 '1111111111222222222233333')

In [106]: len(p.enum_strs[3])
Out[106]: 25
```

**Comment by newville** [comment]
There is definitely a limit in CA -- all data types have hard limits in CA.  I can believe it is 25 characters -- that sounds right.   I thought it might have been 29.   All string lengths in CA are remarkably short from the point-of-view of workstations in 2020.

An enum is not really a list of strings.  It is a set of possible (up to 16, I believe) discrete values with a name associated with each of those values.

**Comment by tacaswell** [comment]
It looks like libca does limit the length to 25 (+1 for null) and 16 enum values (see https://github.com/epics-base/epics-base/blob/d0c4cc0cec8d31b88ee480d2d7f007f17cf0cdbf/modules/ca/src/client/db_access.h#L38-L40).  

Working on a PR to caproto to reject setting too long or too many enums.

**Comment by vstadnytskyi** [comment]
This issue has been resolved with a pull-request #194

**Comment by tacaswell** [comment]
xref https://github.com/caproto/caproto/pull/557

**Comment by vstadnytskyi** [comment]
> It looks like libca does limit the length to 25 (+1 for null) and 16 enum values (see https://github.com/epics-base/epics-base/blob/d0c4cc0cec8d31b88ee480d2d7f007f17cf0cdbf/modules/ca/src/client/db_access.h#L38-L40).
> 
> Working on a PR to caproto to reject setting too long or too many enums.

This will be nice. I have created a test enum PV but I cannot select fields that are exceeding 25 characters.
