### ISSUE TITLE
Discrepancy between caput() behavior and documentation

### ISSUE THREAD

**Issue by daykin** [pyepics/pyepics#198]
Hello,

I am not sure if this is the intended behavior, but if a PV does not exist, caput() returns None instead of a negative number like the documentation says.
Ex: 
```
import epics
print(caput("Brfxxccxxmnpcccclllmmnprxvclmnckssqlbb11116", 1, timeout=1))
```
output:
```
cannot connect to Brfxxccxxmnpcccclllmmnprxvclmnckssqlbb11116
None
```

**Comment by newville** [comment]
fixed in master branch
