### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by hhslepicka** [pyepics/pyepics#206]
Hi @newville , 
Would it be possible to get a new release of pyepics with the latests fixes?

**Comment by newville** [comment]
@hhslepicka @klauer  Oh, yes very sorry for the delay (crazy time and the APS had a 1-week-shutdown).  Ken asked about that last week too.  Will tag and push 3.4.2 right away.

**Comment by hhslepicka** [comment]
@newville no problem at all... I just opened the issue so we can keep track of it.

**Comment by klauer** [comment]
Thanks, @newville! 

On the positive side, it shows pyepics is a vital part of several facilities' software stacks when people are clamoring for a new release. 👍

**Comment by danielballan** [comment]
Just chiming in to pile on the thanks -- much appreciated, @newville!

**Comment by newville** [comment]
@danielballan @klauer @hhslepicka  Thanks!  I think most of the changes here were really from @klauer, @MikeHart85, @hhslepicka, and @vstadnytskyi .  I just tagged and released this, and only after being asked nicely twice!

I keep hoping to try our adl2pydm and start really using PyDM!
