### ISSUE TITLE
[feat&question] Use asyncio instead of callback

### ISSUE THREAD

**Issue by onichandame** [pyepics/pyepics#207]
Is pyepics planning to use the python 3 asyncio?

**Comment by newville** [comment]
@onichandame  I think we are not *planning* to use.  CA sort of uses a different approach to events/callbacks. But maybe there could be some routines to help encapsulate `await`ing and `yield`ing for CA traffic.  

What are you trying to do?

**Comment by onichandame** [comment]
When I invoked an async coroutine  in a callback function of say camonitor, a thread-safety problem occurred as the callback seemed to be run in another thread, however, the coroutine was not invoked in a thread-safe way. Using `asyncio.run_coroutine_threadsafe` solved the problem.

This led me to think about the design of CA functions. Apparently, a Pub/Sub mechanism like camonitor requires the callback design, but this does not stop us from using `asyncio`. The single-threaded asynchronous pattern can achieve what once required multi-thread programming. It does not require us to concern thread stuff so the code can be made more robust.

I know I am very biased towards the asynchronous pattern so please let me know more about the concerns behind the current design. :>

**Comment by newville** [comment]
@onichandame  Well, there are many options for how to program for multiple events.  I hesitate to say that what I do is "normal" or "best practice" but I run my beamline with many different pyepics-based programs (including long-running server-side programs and GUI apps) and basically never use asyncio or use python threads with CA (though I do use python threads for other i/o bound tasks).   

Like some other large-scale event-handling libraries, the CA library has its own event loop and gives programmers the ability to uses callbacks which are called asynchronously (by default) when events happen.  Pyepics more or less "just" wraps that C library.  When you subscribe to a CA Channel or create a pyepics PV, that CA event-loop will call Python methods when events (for example, the value updated) happen for that PV. 

> When I invoked an async coroutine in a callback function of say camonitor, a thread-safety problem occurred as the callback seemed to be run in another thread, however, the coroutine was not invoked in a thread-safe way. Using asyncio.run_coroutine_threadsafe solved the problem.

Any callback function you define will be called by that CA event-loop and be "in that CA thread", not in the main thread of the program.

If you have your own event-loops or event-timing model or a GUI event-loop, it's often helpful to use the CA callbacks only to mark that an event happened and then act on that from your main thread.

**Comment by onichandame** [comment]
Many thanks for clarifying the mechanism behind pyepics. Now I understand that by invoking CA library, a different event loop than the main loop has to be created.
