### ISSUE TITLE
PV status/severity -- potential error in the docs?

### ISSUE THREAD

**Issue by NichtJens** [pyepics/pyepics#212]
I was under the impression that `pv.status` and `pv.severity` are equivalent to the alarms defined in:
https://git.launchpad.net/epics-base/tree/src/libCom/misc/alarmString.c?h=3.15

However, the docs say:

>`pv.status`
>    The PV status, which will be **1** for a Normal, connected PV.

and

> _status_: the status of the PV (**1** for OK)

If my reading of the alarm strings is correct, the status for a normal and successfully connected PV is **0** there. The results of `pv.status` I am seeing, also seem to be consistent with the alarm strings and not with the pyepics docs.

**Comment by newville** [comment]
@NichtJens Oh thanks, yes I agree the doc is wrong there.   Will fix.

**Comment by newville** [comment]
@NichtJens Fixed in master branch.  I will push a new minor release (3.4.3) and publish docs soon-ish (hopefully today).

**Comment by NichtJens** [comment]
@newville Great!

It might be worth showing the conversion table from status number to string in the docs as well. Or simply pointing to `alarmString.c`. Even better would be an actual dict / conversion function. Would you be interested in a PR for the latter?

**Comment by newville** [comment]
@NichtJens yes, I agree that status/severity string messages would be very nice.  A PR for that would be most welcome!

**Comment by klauer** [comment]
If we're targeting only Python 3 now, `enum.IntEnum` can clean these up nicely while providing both integer values and convenient user-facing representations (`AlarmStatus.NO_ALARM` <-> `0`).

**Comment by newville** [comment]
@klauer +1 from me - I think going Py3.6+ would allow a lot of cleanups and modernization.  (and I guess that's a reason to leave the tests alone for a while).

**Comment by NichtJens** [comment]
If I am not mistaken, `enum` only nicely allows this direction: `AlarmStatus.NO_ALARM` -> `0` ...

But how do you use them for this direction: `0` -> `AlarmStatus.NO_ALARM` ?

I would think the former case is not really needed here, though. We _have_ `pv.status` and _want_ a human-readable string (or enum entry name, if we go with those). I don't see how we _have_ the string and _want_ the error code.

I would have gone with a dict `{0: "NO_ALARM", ...}`. It could even be a list/tuple, but then the indices are not as explicit, which might cause problems if -- however unlikely -- a code gets removed from the middle of the range.

But maybe I am missing something obvious.

**Comment by klauer** [comment]
```python
In [1]: class AlarmStatus(enum.IntEnum):
    NO_ALARM = 0
    READ = 1
    WRITE = 2
    ...

In [2]: AlarmStatus(0)
Out[2]: <AlarmStatus.NO_ALARM: 0>

In [3]: AlarmStatus(0).name
Out[3]: 'NO_ALARM'

In [4]: AlarmStatus['NO_ALARM']
Out[4]: <AlarmStatus.NO_ALARM: 0>

In [5]: AlarmStatus['NO_ALARM'].value
Out[5]: 0

In [6]: AlarmStatus(0) == 0
Out[6]: True

In [7]: AlarmStatus['NO_ALARM'] == 0
Out[7]: True
```

With a basic `int` or `str`, once you get the value, there's no going back. The above is quite flexible, in my opinion. A simple definition of `__repr__` can also be usd to just show `'NO_ALARM'` if the above is deemed too verbose.

**Comment by NichtJens** [comment]
Ah! I see. I never saw the call() variant. In that case, I'd agree.

One other point that came to mind is: Would it make sense to not even go into that direction at all and instead add something like this:

```
pv.status -> 0
pv.char_status -> "no alarm"
```

mimicking how it works for the `value` attribute:

```
pv.value -> 12.0
pv.char_value -> "12.000"
```

**Comment by newville** [comment]
I like the idea of `char_status`.  Maybe make that a read-only property and add a subclass of `enum.IntEnum` like @klauer's `AlarmStatus` (and I probably *would* overwrite `__repr__`) to `dbr.py` so that `PV.char_status` just fetched the alarm name?
We could update the "PV info" to include that.

**Comment by NichtJens** [comment]
Yes, that sounds very nice. I will give it a shot.

**Comment by NichtJens** [comment]
Two more questions:

1. Should there be any precaution for running in Python <3.4 (which is the version that introduced `enum`)?

2. Since `IntEnum` works for comparisons with actual integers, it would be possible to change `pv.status` to return them without regression for code that makes such comparisons. In that case, `status` would return the corresponding `IntEnum` member, and `char_status` could return the string representation or `char_status` would not be needed after all (printing would be human-readable anyway)?

And another note:

- Python 3.6 introduced `_missing_` to `enums`, which is "a lookup function used when a value is not found". This is useful for catching unforeseen (/newly implemented) error codes. An alternative would be a try/except like this:
```
@property
def char_status(self):
    "character string representation of the pv status"
    try:
        return dbr.AlarmStatus(self.status).name
    except ValueError:
        return "unknown"
```

As said, this makes Python 3.4 the minimal version. If Python 3.6 as minimal version is acceptable, going with `_missing_` is a bit cleaner. This depends also on what the answer is for question 1 above. (And just to have mentioned it, going with a dict would allow to keep the minimal Python version as it is.)

**Comment by newville** [comment]
@NichtJens  I would say that if we're dropping support for Python 2.7 that we go all the way to 3.6+.  

Python 3.5 is actually at end-of-life (as of this week).   It was understandable that people were stuck with Python 2 for a long time and still needed updates to pyepics.  It's less understandable how people could be stuck with Python 3.5 or older and still need updates to pyepics.  

As it happens, Python 3.6 also provides several nice features that we can start to rely on.  I was not aware of `Enum._missing_`, but I think it is OK to use it.   One feature to be cautious about that got me recently is that Enum starts counting at 1 by default.

**Comment by NichtJens** [comment]
In that case, I think this is already sufficient:
- https://github.com/NichtJens/pyepics/commit/2a3f9f016c6060b22e1db51a9e511580f64f4c26
- https://github.com/NichtJens/pyepics/commit/9bba6e9ee1a72be9bf46452dbf731246cf42f4dc

**Comment by newville** [comment]
@NichtJens Yes, that looks really good. Thanks!

As in #213, I'll plan on tagging the current master as 3.4.3 and pushing that out (later today or perhaps tomorrow) and then change the requirements (and testing) for the master branch to be Py3.6+ and deliberately remove the `utils2.py` code and Python2 stuff in `setup.py`.  Then we can merge a PR from your branch as the first Py3.6+ change.   We don't have to update all the code for Py36 immediately, but we can start to ;).

**Comment by NichtJens** [comment]
Sounds good! Then I'll go ahead and create the PR.

**Comment by newville** [comment]
@NichtJens closing this -- I think is resolved....
