### ISSUE TITLE
pyepics version 3.5.0: end of life for Python2.7 and Python 3.5

### ISSUE THREAD

**Issue by newville** [pyepics/pyepics#213]
@klauer @hhslepicka.  I plan to push a minor release (3.4.3) from the minor changes made since 3.4.2. 

I propose that this be the final version to support Python 2.7 or 3.5, and that we plan to release a pyepics 3.5.0 soon-ish (say, November 1) that has no real feature changes from 3.4.3, but requires Python 3.6, and distributes shared libs built with epics base 7.0.4.

I would like to review and maybe revise the testing setup too, but I'm not certain that will change.

Any objections to this?

**Comment by klauer** [comment]
No objections from me.

**Comment by hhslepicka** [comment]
I am good with that! 👍
