### ISSUE TITLE
Install problem on Centos 8

### ISSUE THREAD

**Issue by pheest** [pyepics/pyepics#216]
If I try to install PyEpics 3.4.3 by means of "sudo python3 setup.py install", i get this error:

error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 2] No such file or directory: '/usr/local/lib/python3.6/site-packages/test-easy-install-56815.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.6/site-packages/

This directory does not currently exist.  Please create it and try again, or
choose a different installation directory (using the -d or --install-dir
option).

The /usr/local/lib directory exists. 
I am able to manually create  /usr/local/lib/python3.6/site-packages/ - and can then successfully install pyepics in to that path.

**Comment by newville** [comment]
@pheest sorry for the trouble, but this seems like it is a permissions problem, not actually related to pyepics.   I have no idea what that `test-easy-install-...` file or directory is supposed to do!

FWIW, pyepics has installed for me on a few CentOS8 instances without incident, though I typically using python3.8 or an environment such as anaconda python.  I don't recall having to build  /usr/local/lib/python3.6/site-packages/ by hand. But I may have installed other site-packages.  I probably installed with  `sudo pip install  pyepics` on all of these systems.  Maybe that is the difference?  

So, I'm not sure what we can do about it, but we can leave this open so it is easier to find and see if others have similar problems.

**Comment by pheest** [comment]
This issue started for me after I updated the Centos 8 install through 'yum update'.
I believe it used to work (same Centos 8).

Did you update Centos, before attempting the install?

**Comment by newville** [comment]
@pheest 
> Did you update Centos, before attempting the install?

Yes, I have run updates.   This definitely has nothing to do with pyepics.
