### ISSUE TITLE
PyCSimpleType appearing in the function native_type (dbr.py)

### ISSUE THREAD

**Issue by hanak** [pyepics/pyepics#218]
Dear Madam/Sir,

This is a question rather than reporting of an issue. If my observation is confirmed, I can work on a solution.

**Problem**
An instance of pyepics 3.4.3 running on Linux (64-bit) encountered the following exception while executing "get" on a string PV published through EPICS 7.0.3.1:
```
TypeError: '>' not supported between instances of '_ctypes.PyCSimpleType' and 'int'
```
with the following stack trace:
```
Exception ignored on calling ctypes callback function: <function _onGetEvent at 0x7f4c8d31d8b0>
Traceback (most recent call last):
File ".../lib/python3.8/site-packages/epics/ca.py", line 747, in _onGetEvent
  result = memcopy(dbr.cast_args(args))
File ".../lib/python3.8/site-packages/epics/dbr.py", line 308, in cast_args
  ntype = native_type(ftype)
File ".../lib/python3.8/site-packages/epics/dbr.py", line 255, in native_type
  if ftype > CTRL_STRING:
```
This was followed with:
```
UserWarning: ca.get('pv') timed out after 5.00 seconds.
```

**Steps to recreate**
Exact sequence of actions is not clear. In fact, this is the first time I am seeing this issue.

**Analysis**
Definitely, the master branch of pyepics changed since the version 3.4.3. Yet, the difference is not significant around this section. While researching the code I noticed the following sequence in the function `cast_args()` (dbr.py) in the current master branch (May 12):
```
    ftype = args.type
    if ftype not in Map:
        ftype = double_t

    ntype = native_type(ftype)
```
The function `cast_args()` is invoked from the function `_onGetEvent()`. If I am reading it right, the function `cast_args()` will receive a structure defined by the class `event_handler_args` (dbr.py). Thus, ftype should be an instance of `ctypes.c_long`. This is supported by the fact that `Map` uses integer keys and `native_type()` tries to treat the argument (`ftype`) as an integer.  Yet, the function `cast_args()` can assign `ftype` with `double_t` which is an instance `_SimpleCData` if it does not find a key in `Map`. This looks quite suspicious. Does I read the code right?

**Thoughts on solution**
I am going to assume the fallback was trying to assume the type is `DOUBLE` if the type is not known to pyepics. Since pyepics receives a pointer to raw memory in the callback, I would consider following:
1. Log a warning (so that corrective action can be taken in pyepics or epics).
2. Reject the unknown type (what if the memory provided by the callback is shorter than the memory footprint of `DOUBLE`).

**Comment by newville** [comment]
@hanak Hm, yeah that all seems weird.  I agree with your assessment and think that section of `cast_args()` should probably be

    ftype = args.type
    if ftype not in Map:
        ftype = DOUBLE

But: I also don't quite understand how one gets to have `_onGetEvent()` called, but have a value for `args.type` be something that is not in the `dbr.Map`.   I know that we do not support the "STS" and "GR" variants, but I think that means that it would be very difficult to make a Python epics.ca Channel that was of one of those types.   I do also see  DBR_STSACK_STRING and  DBR_CLASS_NAME, but I do not actually know what those are ;). 

Could the PV you are connecting to be a DBR_STSACK_STRING?  I don't know how to create one of those.   Maybe the right thing to do is just raise an error saying "unrecognized Channel DBR Type" or similar.

**Comment by hanak** [comment]
Thank you for your response. I agree, I will log an error and avoid processing the callback further if this happens. I will create a pull request once I setup a development environment for pyepics.

Regarding the PV. camonitor gives me:
```
State:            connected
Host:             x.x.x.x:x
Access:           read, write
Native data type: DBF_STRING
Request type:     DBR_STRING
Element count:    1
```
Nevertheless, I have seen it just once while running automated BDD tests on a build machine. Since it has happened once, it will happen again in future. I am just curious what EPICS provided as the field type. Maybe, this will help to uncover the cause.

**Comment by newville** [comment]
@hanak OK, thanks -- still weird that the Channel was connected enough to get a GetEvent callback but have a bad value for `args.type`.  Anyway, changing the `if ftype not in Map:` block seems like the right thing to do.   I'm not sure that `DOUBLE` is the best default value, but I think at that point the code is just trying to make do with a bad situation anyway.

**Comment by newville** [comment]
@hanak if you're willing to make a Pull Request for this, that would be great.  If not, let me know, and I'll make the change to`ftype = DOUBLE`, and maybe add a warning message when this happens.

**Comment by hanak** [comment]
Thank you for your message. The code change is done incl. a unit test:
https://github.com/hanak/pyepics/tree/218-pycsimpletype-appearing-in-the-function-native_type

I just need to setup the test environment so that I can run higher-level tests involving EPICS.

**Comment by hanak** [comment]
Just for documentation purposes, the issue should be addressed through the pull request https://github.com/pyepics/pyepics/pull/219

**Comment by newville** [comment]
@hanak OK, I think this can now be closed
