### ISSUE TITLE
strings to waveforms broken on python3

### ISSUE THREAD

**Issue by newville** [pyepics/pyepics#22]
writing a byte array to a char waveform is broken, leaving trailing junk

sending a string is worse, adding an extra 'b' to the result

sending a length-1 string might be broken too.

**Comment by tacaswell** [comment]
@newville Is this still an issue?  If so can you point me to about where in the code this needs to be fixed?

**Comment by newville** [comment]
@tacaswell  Hi -- I think there still may be some "unexpected features", basically reflecting CA's "strings are  ASCII".   I'm out of town at the moment, and can't verify easily, but I believe that it may still be the case that

``` python 
>>> import epics
>>> pv = epics.PV(CHAR_WAVEFORM_PV)
>>> pv.put('hello')
>>> pv.get(as_string=True)
'hellob'

>>> pv.put(b'hello')
>>> pv.get(as_string=True)
'hello'

```

(again, not verified -- from memory while on travel).    Obviously,  the trailing 'b' was definitely wrong and weird that it was always a trailing 'b'.  

Then again, reading the commit log, this might have been fixed with 56c6db1ed2107766778532d5118c269e4bd19c70 and I'm just not remembering correctly, and was lazy about closing the issue.  All my own stuff is still Python2 only (using wx and matplotlib!),  so I test with Python3 but am not using it for real production work yet.

Then again, at some point the mismatch between Python3 and CA for "strings" might need to be something the user keeps in mind.  A char waveform is pretty close to "bytes", and CA really doesn't do unicode, so a more complete "fix" might be hard.   It might be possible/necessary to special-case all "as_string" handling.  There is already some of this, so I'm not opposed to it, just that might get more elaborate.

**Comment by newville** [comment]
@tacaswell  -- I verified that this *is* still a problem with python 3.4.1 and pyepics master branch.

**Comment by newville** [comment]
provisional fix with PR #35 -  this was partially done long ago and fell out of sight.   I think it is right, but it could stand more rigorous testing.

**Comment by klauer** [comment]
This has been working well for us at NSLS-II. Closing.

**Comment by tacaswell** [comment]
Actually went into code base via #44
