### ISSUE TITLE
pyepics crashes process on shutdown randomly

### ISSUE THREAD

**Issue by hanak** [pyepics/pyepics#228]
**Problem**
I am using pyepics with behave in order to run BDD on IOCs. I am experiencing random crashes on the shutdown. There, libca reports "CA client library tcp receive thread terminating due to a non-standard C++ exception" and terminates behave. This is detected as test failure.

I was not able to find the cause, yet. Unfortunately, there is an exception trap in libca which logs the information and consumes the exception. This prevents the exception to bubble-up into the OS so that a debugger might get is easily. Yet, recently I run an instance which offered more information about potential cause:
```
Exception ignored on calling ctypes callback function: <function _onMonitorEvent at 0x7f2f72772160>
Traceback (most recent call last):
  File ".../site-packages/epics/ca.py", line 682, in _onMonitorEvent
Exception ignored on calling ctypes callback function: <function _onMonitorEvent at 0x7f2f72772160>
Traceback (most recent call last):
  File ".../site-packages/epics/ca.py", line 682, in _onMonitorEvent
    entry = _get_cache_by_chid(args.chid)
  File ".../site-packages/epics/ca.py", line 472, in _get_cache_by_chid
    entry = _get_cache_by_chid(args.chid)
  File ".../site-packages/epics/ca.py", line 472, in _get_cache_by_chid
    pvname = BYTES2STR(libca.ca_name(dbr.chid_t(chid)))
AttributeError: 'object' object has no attribute 'ca_name'
CA client library tcp receive thread terminating due to a non-standard C++ exception
FATAL: exception not rethrown
```

**Early Analysis**
Looking at `ca.py`, the variable `libca` is set to `_LIBCA_FINALIZED` on shutdown. `_LIBCA_FINALIZED` is `object`. So, in theory I might be looking at concurrency issue in pyepics: `_onMonitorEvent()` arrives while `libca` is set or being set to `_LIBCA_FINALIZED`.  Since `_onMonitorEvent()` (`ca.py`) does not expect it, it tries to use `libca` as if it was a valid object. This is suspicious but it could be just fine depending on intended use. Is this expected?

During the test run I execute multiple tests. In order to reset the environment prior each test, I use `clear_cache()` (`ca.py`). Sometimes, I shut down IOCs prior a test, too. Yet, this is not the case here. If I compare `clear_cache()` with very similar sequence in `finalize_libca()`, I can see that `clear_cache()` does not include a loop which calls `clear_channels()` on all cached items prior clearing the cache. It just clears the cache (python list). This is suspicious to me. I did not research it deeper but it feels like this might leave a callback still registered with CA. Could this be the case?

**Comment by newville** [comment]
@hanak   For sure, crash-on-exit can be hard to diagnose and fix.  But it's also really hard for me (or, likely, anyone else) to give a very specific answer if you do not provide any code.  
You say you've run multiple tests, but gave few details of what those were.  We simply do not know what you are doing.  

As you see in the code, `ca.finalize_epics()` is run when exiting Python, which will occur very late in the life of the process.  During this time, Python will be cleaning up memory and deleting objects.  For sure, if `ca.finalize_epics()` did nothing, there would be a good chance the CA library could try to run one of the registered callback functions, and that would make some assumptions about objects that may have been deleted, causing access violations. 

There are several safety mechanisms in place in `ca.finalize_libca()` to try to make sure that CA connections are cleaned up and removed to prevent such crashes on exit.   Using _LIBCA_FINALIZED  is one of those.   These all seem to work reasonably well for me, and I don't hear a lot of complaints about this, but I can certainly believe that there may be cases that we don't catch everything. 

Unless you are using multi-processing, and creating PVs in multiple processes,  I think that `ca.clear_cache()` should not be necessary.   Can you give any more hints about what you are doing or provide an example that shows the problem?

**Comment by hanak** [comment]
@newville Thank you for your comments. While I was preparing my response, I realized there might be a chance to recreate conditions I think I am running into using a python script. This made me curious. I would like to give it a try before I respond to your comment. Maybe, I will be lucky to see behavior similar to behavior I see on a more complex system.

**Comment by hanak** [comment]
@newville I think I managed to create a script which demonstrates the problem (at least it does so on my VM). Yet, let us start with more details:
* The issue occurs when Python is about to exit. It happens randomly. Sometimes, it exits fine. Sometimes, I got just a message from libca about non-standard exception and behave is terminated with an error. And, this time I was lucky to see more than that.
* `ca.finalize_libca()` might be perfectly fine. It is just that it does not prevent callbacks from being invoked. That is the current hypothesis.
* I run BDD tests using behave as the runner. The runner uses Python as a runtime environment.
* One of the key aspects of BDD tests is ability to revert everything back to the initial state prior running next scenario. Ideally, the test should yield the same outcome regardless whether it runs alone or it runs first or in the middle or the last. In fact, I might even terminate and start a new IOC or restart the same IOC between tests. Therefore, I call `ca.clear_cache()` to make sure we limit state leaks across tests. I might have seem some side effects without clearing the cache. I did not leave notes to my future self while I was resolving this so this thought might be inaccurate.

I tried to recreate the issue on something much simpler: an IOC and a simple script. The script is available at https://github.com/hanak/pyepics-clear-cache-test. It expects an IOC which increases a PV every 0.1 second. This increases our chance to hit the window of opportunity when the Python is shutting down. I run a bash script which counted how many times python has crashed (I have seen SIGSEGV or ABORTED). The results I have measured (environment: single core VM, Debian 64-bit, Python 3.9.2, pyepics 3.4.3) are:
* Call `clear_cache()`: 55% crashes (100 executions)
* Call `clear_channel()` for every channel in the cache prior `clear_cache()`: 0% crashes (100 executions)
Thus, it seems to me `clear_cache()` drops references but leaves callbacks registered in libca.

What do you think?

**Comment by newville** [comment]
@hanak   I'm having a hard time following you.


>The issue occurs when Python is about to exit. It happens randomly. Sometimes, it exits fine. Sometimes, I got just a message from libca about non-standard exception and behave is terminated with an error. And, this time I was lucky to see more than that.

> ca.finalize_libca() might be perfectly fine. It is just that it does not prevent callbacks from being invoked once it disconnects libca. That is the current hypothesis.

I don't know.  Can you provide evidence for that?

> I run BDD tests using behave as the runner. The runner uses Python as a runtime environment.
>One of the key aspects of BDD tests is ability to revert everything back to the initial state prior running next scenario. Ideally, the test should yield the same outcome regardless whether it runs alone or it runs first or in the middle or the last. In fact, I might even terminate and start a new IOC or restart the same IOC between tests. Therefore, I call ca.clear_cache() to make sure we limit state leaks across tests. I might have seem some side effects without clearing the cache. I did not leave notes to my future self while I was resolving this so this thought might be inaccurate.

As it turns out, I don't know what BDD means.   Is that important here?

"Therefore, I call ca.clear_cache() to make sure we limit state leaks across tests." seems like it might be your main problem to me.   

Are you starting IOCs from Python proceses?  Or are you using pyepics from within an IOC?  I don't really understand what you are trying to do, and the only code you've given seems like some artificial attempt to break something....


> I tried to recreate the issue on something much simpler: an IOC and a simple script. The script is available at https://github.com/hanak/pyepics-clear-cache-test. It expects an IOC which increases a PV every 0.1 second. This increases our chance to hit the window of opportunity when the Python is shutting down. I run a bash script which counted how many times python has crashed (I have seen SIGSEGV or ABORTED). The results I have measured (environment: single core VM, Debian 64-bit, Python 3.9.2, pyepics 3.4.3) are:

I guess I don't understand why your script is repeatedly calling clear_cache(), and apparently from the main thread.  And then apparently refilling the cache with new connections to the same Channel.    Is your goal to cause crashes on exit or to use the library?

> Call clear_cache(): 55% crashes (100 executions)
> Call clear_channel() for every channel in the cache prior clear_cache(): 0% crashes (100 executions). 
> It seems to me clear_cache() drops references but leaves callbacks registered in libca.

And what happens if you do neither?

> What do you think?

Not sure.  I can certainly believe that repeatedly calling `clear_cache()` is a bad idea.

**Comment by hanak** [comment]
@newville Thank you for your comments. I understand your viewpoint on the matter. Thus, let me answer your questions. Since the text is quite long already, let me add your question starting with Q: and provide and a answer starting with A:. Hopefully, this is not going to be confusing.

Q1: I don't know. Can you provide evidence for that (that the callbacks are not disconnected)?

A1: In a printout of a crash (the description of the problem above) there is a line "`AttributeError: 'object' object has no attribute 'ca_name'`" which refers to the code `libca.ca_name(dbr.chid_t(chid))`. Since `ca.finalize_libca()` sets `libca` to `object()` I can draw a link between `ca.finalize_libca()` and the crash. Would you find this link too weak to be real?

Q2: As it turns out, I don't know what BDD means. Is that important here?

A2: Not important. It is just context. I think I reacted to your comment about last of details on tests I am running. The tests were BDD tests of IOCs. The following paragraph provides somewhat brief introduction. Do not hesitate to skip it.

BDD stands for "Behavior-Driven Development". BDD tries to connect the world of requirements and the world of code. It enables writing requirements such that they can run as tests at the same time. This has a few consequences: BDD tests focus on testing behaviour of larger components (in this case an IOC) and a BDD test may be defined by a business analysts and/or a tester who may not have skills develop a unit test in pytest. Example of a test:
```
Given the door indicator is powered
And the door is closed
When the user opens the door
Then the door indicator turns on
```

Q3: Are you starting IOCs from Python proceses? Or are you using pyepics from within an IOC?

A3: Python starts and stops the IOCs. There is no Python in the IOC.

Q4: Is your goal (of the script) to cause crashes on exit or to use the library?

A4: The goal of the script is to demonstrate that there is a race-condition in pyepics which may cause the library to crash on exit. Production code behaviour depends on executed test. So, that probability of the crash is lower. Yet, production code runs on in a build system on every pull-request automatically. Thus, even a lower probability is annoying enough to try to address it.

Q5: And what happens if you do neither (i.e. do not call `clear_cache()`)?

A5: If `clear_cache()` is not called, pyepics does not crash. Yet, before we call it the solution and close the case I would like to state I need the connections to start anew even if the name of the PV is the same because I restart IOCs. Keeping the cache creates dependency on order of test execution. Since I have unpleasant experience with cross-test dependencies from earlier, I try to avoid it as much as I can.

Q6: I can certainly believe that repeatedly calling `clear_cache()` is a bad idea.

A6: I agree because I believe `clear_cache()` enables a race condition. And, I think there is a solution to it: disconnect content of the cache from EPICS (i.e. call `clear_channel()`) prior clearing the cache. The test script stops crashing when applied but I am not sure whether there are no other side-effects. Therefore, I asked before submitting a pull-request.

**Comment by newville** [comment]
@hanak 

>> Q5: And what happens if you do neither (i.e. do not call clear_cache())?

> A5: If clear_cache() is not called, pyepics does not crash. Yet, before we call it the solution and close the case I would like to state I need the connections to start anew even if the name of the PV is the same because I restart IOCs. Keeping the cache creates dependency on order of test execution. Since I have unpleasant experience with cross-test dependencies from earlier, I try to avoid it as much as I can.

Well, it is good news that it does not crash when `clear_cache()` is not called.

I am not sure I understand why you need the connection to start anew just because you restart an IOC.   In general, handling the loss of connection as when restarting an IOC is something that CA handles well -- the PV object gets "connection callbacks" when the connection state changes.   It is definitely not necessary to start all client processes when an IOC starts.    

But, maybe you want to do that as part of your tests.  That should be OK.    Well, maybe you want to explicitly run `finalize_libca()`?    Or, why do you want to clear the CA cache but not fully re-connect to the Epics CA library?

That said, `clear_cache()` is clearly showing some problem when called repeatedly within a process.  Some part of the "disconnect PVs" seems to need fixing, though I'm not sure what that is.

I might also encourage you to ask yourself what your tests are trying to simulate and whether those tests really need to be run in a single process.

**Comment by hanak** [comment]
@newville  Thank you for your comments and suggestions.

C1: I am not sure I understand why you need the connection to start anew just because you restart an IOC.
* A1: EPICS and pyepics can handle loss of connectivity. I agree. Yet, I think I was running into various durations each step in a scenario may take depending on state of pyepics while using `caget` and `caput`. Sadly, I do not have notes from the time I was making the decision to use `clear_cache()`. I am sorry.

C2: Or, why do you want to clear the CA cache but not fully re-connect to the Epics CA library?
* A2: I will give it a try.

C3: That said, `clear_cache()` is clearly showing some problem when called repeatedly within a process.
* A3: I think I should point out that I have tried to call it just once (per process) and it still causes a crash on exit in some number of cases. Should I commit the script which demonstrates the vulnerability into pyepics repository?

C4: I might also encourage you to ask yourself what your tests are trying to simulate and whether those tests really need to be run in a single process.
* A4: I think I can run as many processes as OS can handle. The cost is more complex runner and longer startup. The tests verify interaction with and between IOCs. And, this works very well as is. It is just the test runner that causes me troubles. Since the source seems to be inside pyepics, I can move pyepics in a (REST-like) process and start it as needed. Yet, I think pyepics is a nice library. Thus, I wanted to see whether it can be improved before I just work around it. Maybe, this can save someone from some frustration in future.

**Comment by newville** [comment]
@hanak 

>> C1: I am not sure I understand why you need the connection to start anew just because you restart an IOC.

> A1: EPICS and pyepics can handle loss of connectivity. I agree. Yet, I think I was running into various durations each step in a scenario may take depending on state of pyepics while using caget and caput. Sadly, I do not have notes from the time I was making the decision to use clear_cache(). I am sorry.

Yeah, I do sympathize, but it is hard to know what might be going on.  For sure, restarting an IOC does not "normally" cause problems for me... but that's not to say that it is always perfect or rigorously tested. 

>> C3: That said, clear_cache() is clearly showing some problem when called repeatedly within a process.

> A3: I think I should point out that I have tried to call it just once (per process) and it still causes a crash on exit in some number of cases. Should I commit the script which demonstrates the vulnerability into pyepics repository?

Yes.   

I don't know for sure what `clear_cache()` is missing,  but it might make sense to move some of that "cancel all callbacks" code that is in `finalize_libca()` so that it is also called by `clear_cache()` for all PVs.   That would make `clear_cache()` much more like `finalize_libca()` at least for the current process/context (and maybe then `finalize_libca()` is not much more than "run clear_cache() for all contexts").  Again, I'd be a little cautious about doing this, but feel free to play around with that and make a PR.

**Comment by hanak** [comment]
@newville 
Just to keep events linked, I have submitted a pull request containing a minimalistic fix and a test:
https://github.com/pyepics/pyepics/pull/229

**Comment by hanak** [comment]
@newville Thank you for the review and merging the pull request. There is a new automated test covering the issue. Assuming the tests are run from time to me, it should help. As a next step in software development, I would hand over the issue to another person who would confirm whether the problem is gone or not independently on me. Then, the team would consider the issue as done. Yet, I am not familiar with workflow on this project. What should we do with this issue?

**Comment by newville** [comment]
@hanak Well, with the code merged and tests in place, I think we can close this Issue.
