### ISSUE TITLE
The issue of installed pyepics 

### ISSUE THREAD

**Issue by PeiyuQuan** [pyepics/pyepics#239]
Hello Matt

I just installed pyepics in Ubuntu 20.04. When I test it, The result as follows: I don't know why lost softIoc.dbd in ~/epics/pyepics/tests/Setup.

quan@PC98545:~/epics/pyepics/tests/Setup$ softIoc ./st.cmd
errlogInit(5000)
epicsEnvSet("IOC","iocPyEpicsTest")
dbLoadDatabase("softIoc.dbd")
filename="../dbStatic/dbLexRoutines.c" line number=270
No such file or directory dbRead opening file softIoc.dbd
dbLoadRecords("pydebug.db", "P=PyTest:")
dbLoadRecords("pyclearcache.db", "P=PyTestClearCache:")
iocInit
Starting iocInit
############################################################################
############################################################################
iocRun: All initialization complete
epics> exit

quan@PC98545:~/epics/pyepics/tests/Setup$ ls
pyclearcache.db  pydebug.db  simulator.py  st.cmd

quan@PC98545:~/epics/pyepics$ python setup.py install
running install
running bdist_egg
running egg_info
writing pyepics.egg-info/PKG-INFO
writing dependency_links to pyepics.egg-info/dependency_links.txt
writing requirements to pyepics.egg-info/requires.txt
writing top-level names to pyepics.egg-info/top_level.txt
reading manifest file 'pyepics.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README.txt'
warning: no files found matching 'Changelog'
warning: no files found matching 'publish.sh'
warning: no files found matching '*.bat'
warning: no previously-included files found matching '*.pyc'
warning: no previously-included files found matching 'core.*'
warning: no previously-included files found matching '*~'
warning: no previously-included files found matching '*.pdf'
warning: no files found matching '*' under directory 'dlls'
warning: no previously-included files matching '*' found under directory 'doc/_build'
warning: no previously-included files matching '*.pdf' found under directory 'doc'
warning: no previously-included files matching '*' found under directory 'tests/Misc'
writing manifest file 'pyepics.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
UPDATING build/lib/epics/_version.py
set build/lib/epics/_version.py to '3.5.1'
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/epics
copying build/lib/epics/pv.py -> build/bdist.linux-x86_64/egg/epics
creating build/bdist.linux-x86_64/egg/epics/devices
copying build/lib/epics/devices/mca.py -> build/bdist.linux-x86_64/egg/epics/devices
copying build/lib/epics/devices/ordereddict.py -> build/bdist.linux-x86_64/egg/epics/devices
copying build/lib/epics/devices/ad_overlay.py -> build/bdist.linux-x86_64/egg/epics/devices
copying build/lib/epics/devices/ad_perkinelmer.py -> build/bdist.linux-x86_64/egg/epics/devices
copying build/lib/epics/devices/xspress3.py -> build/bdist.linux-x86_64/egg/epics/devices
copying build/lib/epics/devices/bo.py -> build/bdist.linux-x86_64/egg/epics/devices
copying build/lib/epics/devices/ad_mca.py -> build/bdist.linux-x86_64/egg/epics/devices
copying build/lib/epics/devices/ai.py -> build/bdist.linux-x86_64/egg/epics/devices
copying build/lib/epics/devices/__init__.py -> build/bdist.linux-x86_64/egg/epics/devices
copying build/lib/epics/devices/bi.py -> build/bdist.linux-x86_64/egg/epics/devices
copying build/lib/epics/devices/ad_image.py -> build/bdist.linux-x86_64/egg/epics/devices
copying build/lib/epics/devices/ad_base.py -> build/bdist.linux-x86_64/egg/epics/devices
copying build/lib/epics/devices/transform.py -> build/bdist.linux-x86_64/egg/epics/devices
copying build/lib/epics/devices/ad_fileplugin.py -> build/bdist.linux-x86_64/egg/epics/devices
copying build/lib/epics/devices/srs570.py -> build/bdist.linux-x86_64/egg/epics/devices
copying build/lib/epics/devices/struck.py -> build/bdist.linux-x86_64/egg/epics/devices
copying build/lib/epics/devices/scaler.py -> build/bdist.linux-x86_64/egg/epics/devices
copying build/lib/epics/devices/ao.py -> build/bdist.linux-x86_64/egg/epics/devices
copying build/lib/epics/devices/scan.py -> build/bdist.linux-x86_64/egg/epics/devices
copying build/lib/epics/device.py -> build/bdist.linux-x86_64/egg/epics
copying build/lib/epics/multiproc.py -> build/bdist.linux-x86_64/egg/epics
copying build/lib/epics/ca.py -> build/bdist.linux-x86_64/egg/epics
copying build/lib/epics/alarm.py -> build/bdist.linux-x86_64/egg/epics
creating build/bdist.linux-x86_64/egg/epics/autosave
copying build/lib/epics/autosave/save_restore.py -> build/bdist.linux-x86_64/egg/epics/autosave
copying build/lib/epics/autosave/__init__.py -> build/bdist.linux-x86_64/egg/epics/autosave
creating build/bdist.linux-x86_64/egg/epics/clibs
creating build/bdist.linux-x86_64/egg/epics/clibs/darwin64
copying build/lib/epics/clibs/darwin64/libca.dylib -> build/bdist.linux-x86_64/egg/epics/clibs/darwin64
copying build/lib/epics/clibs/darwin64/libComPYEPICS.dylib -> build/bdist.linux-x86_64/egg/epics/clibs/darwin64
copying build/lib/epics/clibs/darwin64/README -> build/bdist.linux-x86_64/egg/epics/clibs/darwin64
creating build/bdist.linux-x86_64/egg/epics/clibs/linuxarm
copying build/lib/epics/clibs/linuxarm/libca.so -> build/bdist.linux-x86_64/egg/epics/clibs/linuxarm
copying build/lib/epics/clibs/linuxarm/libComPYEPICS.so -> build/bdist.linux-x86_64/egg/epics/clibs/linuxarm
copying build/lib/epics/clibs/linuxarm/README -> build/bdist.linux-x86_64/egg/epics/clibs/linuxarm
copying build/lib/epics/clibs/__init__.py -> build/bdist.linux-x86_64/egg/epics/clibs
creating build/bdist.linux-x86_64/egg/epics/clibs/win64
copying build/lib/epics/clibs/win64/caRepeater.exe -> build/bdist.linux-x86_64/egg/epics/clibs/win64
copying build/lib/epics/clibs/win64/ca.dll -> build/bdist.linux-x86_64/egg/epics/clibs/win64
copying build/lib/epics/clibs/win64/Com.dll -> build/bdist.linux-x86_64/egg/epics/clibs/win64
copying build/lib/epics/clibs/win64/README -> build/bdist.linux-x86_64/egg/epics/clibs/win64
creating build/bdist.linux-x86_64/egg/epics/clibs/win32
copying build/lib/epics/clibs/win32/caRepeater.exe -> build/bdist.linux-x86_64/egg/epics/clibs/win32
copying build/lib/epics/clibs/win32/ca.dll -> build/bdist.linux-x86_64/egg/epics/clibs/win32
copying build/lib/epics/clibs/win32/Com.dll -> build/bdist.linux-x86_64/egg/epics/clibs/win32
copying build/lib/epics/clibs/win32/README -> build/bdist.linux-x86_64/egg/epics/clibs/win32
creating build/bdist.linux-x86_64/egg/epics/clibs/linux64
copying build/lib/epics/clibs/linux64/libca.so -> build/bdist.linux-x86_64/egg/epics/clibs/linux64
copying build/lib/epics/clibs/linux64/libComPYEPICS.so -> build/bdist.linux-x86_64/egg/epics/clibs/linux64
copying build/lib/epics/clibs/linux64/README -> build/bdist.linux-x86_64/egg/epics/clibs/linux64
creating build/bdist.linux-x86_64/egg/epics/clibs/linux32
copying build/lib/epics/clibs/linux32/libca.so -> build/bdist.linux-x86_64/egg/epics/clibs/linux32
copying build/lib/epics/clibs/linux32/libComPYEPICS.so -> build/bdist.linux-x86_64/egg/epics/clibs/linux32
copying build/lib/epics/clibs/linux32/README -> build/bdist.linux-x86_64/egg/epics/clibs/linux32
copying build/lib/epics/motor.py -> build/bdist.linux-x86_64/egg/epics
creating build/bdist.linux-x86_64/egg/epics/wx
copying build/lib/epics/wx/ordereddict.py -> build/bdist.linux-x86_64/egg/epics/wx
copying build/lib/epics/wx/motorpanel.py -> build/bdist.linux-x86_64/egg/epics/wx
copying build/lib/epics/wx/ogllib.py -> build/bdist.linux-x86_64/egg/epics/wx
copying build/lib/epics/wx/utils.py -> build/bdist.linux-x86_64/egg/epics/wx
copying build/lib/epics/wx/__init__.py -> build/bdist.linux-x86_64/egg/epics/wx
copying build/lib/epics/wx/wxlib.py -> build/bdist.linux-x86_64/egg/epics/wx
copying build/lib/epics/wx/motordetailframe.py -> build/bdist.linux-x86_64/egg/epics/wx
copying build/lib/epics/utils.py -> build/bdist.linux-x86_64/egg/epics
creating build/bdist.linux-x86_64/egg/epics/compat
copying build/lib/epics/compat/CaChannel.py -> build/bdist.linux-x86_64/egg/epics/compat
copying build/lib/epics/compat/__init__.py -> build/bdist.linux-x86_64/egg/epics/compat
copying build/lib/epics/compat/ca_util.py -> build/bdist.linux-x86_64/egg/epics/compat
copying build/lib/epics/compat/epicsPV.py -> build/bdist.linux-x86_64/egg/epics/compat
copying build/lib/epics/__init__.py -> build/bdist.linux-x86_64/egg/epics
copying build/lib/epics/_version.py -> build/bdist.linux-x86_64/egg/epics
copying build/lib/epics/dbr.py -> build/bdist.linux-x86_64/egg/epics
byte-compiling build/bdist.linux-x86_64/egg/epics/pv.py to pv.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/devices/mca.py to mca.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/devices/ordereddict.py to ordereddict.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/devices/ad_overlay.py to ad_overlay.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/devices/ad_perkinelmer.py to ad_perkinelmer.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/devices/xspress3.py to xspress3.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/devices/bo.py to bo.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/devices/ad_mca.py to ad_mca.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/devices/ai.py to ai.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/devices/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/devices/bi.py to bi.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/devices/ad_image.py to ad_image.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/devices/ad_base.py to ad_base.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/devices/transform.py to transform.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/devices/ad_fileplugin.py to ad_fileplugin.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/devices/srs570.py to srs570.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/devices/struck.py to struck.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/devices/scaler.py to scaler.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/devices/ao.py to ao.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/devices/scan.py to scan.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/device.py to device.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/multiproc.py to multiproc.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/ca.py to ca.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/alarm.py to alarm.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/autosave/save_restore.py to save_restore.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/autosave/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/clibs/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/motor.py to motor.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/wx/ordereddict.py to ordereddict.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/wx/motorpanel.py to motorpanel.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/wx/ogllib.py to ogllib.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/wx/utils.py to utils.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/wx/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/wx/wxlib.py to wxlib.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/wx/motordetailframe.py to motordetailframe.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/utils.py to utils.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/compat/CaChannel.py to CaChannel.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/compat/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/compat/ca_util.py to ca_util.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/compat/epicsPV.py to epicsPV.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/_version.py to _version.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/epics/dbr.py to dbr.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pyepics.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyepics.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyepics.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyepics.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyepics.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
epics.__pycache__.ca.cpython-37: module references __file__
creating 'dist/pyepics-3.5.1-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pyepics-3.5.1-py3.7.egg
removing '/home/quan/anaconda3/lib/python3.7/site-packages/pyepics-3.5.1-py3.7.egg' (and everything under it)
creating /home/quan/anaconda3/lib/python3.7/site-packages/pyepics-3.5.1-py3.7.egg
Extracting pyepics-3.5.1-py3.7.egg to /home/quan/anaconda3/lib/python3.7/site-packages
pyepics 3.5.1 is already the active version in easy-install.pth

Installed /home/quan/anaconda3/lib/python3.7/site-packages/pyepics-3.5.1-py3.7.egg
Processing dependencies for pyepics==3.5.1
Searching for setuptools==40.2.0
Best match: setuptools 40.2.0
Adding setuptools 40.2.0 to easy-install.pth file
Installing easy_install script to /home/quan/anaconda3/bin

Using /home/quan/anaconda3/lib/python3.7/site-packages
Finished processing dependencies for pyepics==3.5.1

**Comment by newville** [comment]
@PeiyuQuan Is that a bug report? I honestly cannot tell.   If you install `pypeics`, does it work?

The tests in the `tests` folder do require an epics installation to run a softioc, which may not be installed with every epics installation (to be clear: having the ability to run an IOC is not required to use pyepics).  The "simulator" script alters the values of PVs defined in the records in the db file that should be running on an IOC in the local network (not necessarily on the same machine).  An IOC and the simulator script need to be running for or tests scripts to pass, as they will check things like getting and setting changing values.

To use `pyepics`, you do not need any of the testing code.
