### ISSUE TITLE
launch new multiprocessing task from pv / camonitor callback

### ISSUE THREAD

**Issue by kingspride** [pyepics/pyepics#241]
Hello,
I'd like to launch a new multiprocess from a camonitor callback function.

but unfortunately, the thread gets created, but never really runs.
example code:
```py
import epics
import time

runner = epics.CAProcess()
run = epics.multiproc.mp.Value("i", True)

def stopper(**kwargs):
    global run
    if kwargs["value"] == 1:
        print("stopping")
        run.value = False

def starter(**kwargs):
    global runner, run
    if kwargs["value"] == 1:
        print("starting")
        runner = epics.CAProcess(name="Runner instance", target=worker, args=(run, "asdf", ))
        runner.start()
        print("ok")

def worker(run, planfile):
    # gets created, but never does anything
    while run.value:
        print(planfile)
        time.sleep(1)

def main():
    global runner
    global run

    epics.camonitor("epics:start", callback=starter)
    epics.camonitor("epics:stop", callback=stopper)
    
    while True:
        # main thread needs to keep running otherwise all childs get terminated
        print(f"runner alive? {runner.is_alive()}")
        time.sleep(1)

if __name__ == "__main__":
    main()
```

![grafik](https://user-images.githubusercontent.com/45198837/202429103-603b8965-43a8-41f9-990e-5b91b199d60c.png)

what can I do?
the manual states that its advisable to do longer work "in a seperate thread" instead of inside the callback.

thanks!

**Comment by kingspride** [comment]
okay. usage of global variables are not the "fine english way" as you'd say in german, but I can definitly use it if there is no other option.

**Comment by newville** [comment]
Well, your `runner`, `run`, `worker`, `starter`, `stopper`, and `main` *are* global variables, and you are using `global` throughout your script.  Another completely normal approach would be to encapsulate that into a class, and have each of those be attributes/methods of the instance of the object (and then nothing would be `global` in your script and instead be owned by `self`).

But also, information and data about CA connections do need to be in "per-process" global data.  That is done behind the scenes, but it can be useful to keep in mind that there is a single CA event loop running within the C-level  CA library.

**Comment by kingspride** [comment]
sure, but initially I didnt want to use at least the global statement. maybe its just personal taste.

the script above was already a later version where I tried a lot of things (bluesky and ophyd devices dont work inside pyepics multiprocesses... :( )
so yeah...

I'll try to make my way though it with globals / classes and see where I get.
thanks so far :)

**Comment by newville** [comment]
@kingspride well, yeah there is also the question of "multiprocess" is actually what you want, especially in contrast to running multiple processes (ie, launched by the OS).  

I can't help with anything related to ophyd/bluesky - I don't use it.
