### ISSUE TITLE
libca.so: cannot open shared object file

### ISSUE THREAD

**Issue by elderwann** [pyepics/pyepics#244]
Hello,

I tried hard to understand why pyepics doesn’t work on my odroid C4.
I installed python version 3.8 and last pyepics version3.5.1 

Unfortunately, when I start python and after writing :

>>> import epics
>>>  pv=epics.PV('VARIABLE')

The return was : 

/home/odroid/.local/lib/python3.8/site-packages/epics/clibs/linux64/libca.so: cannot open shared object file: No such file or directory

But in reality, the file is in the linux64 folder :  /home/odroid/.local/lib/python3.8/site-packages/epics/clibs/linux64/

I read in the page  [Downloading and Installation — Epics Channel Access for Python (uchicago.edu)](https://cars9.uchicago.edu/software/python/pyepics3/installation.html)  that   “  If these provided versions of libca do not work for you, please let us know. “ ..
Where can I find other libca versions ?

Many thanks.

My environment : Ubuntu mate 20.0,  python 3.8 , pyepics 3.5.1,  cpu archi aarch64,  hardware : odroid C4.

Erwann.

**Comment by newville** [comment]
I believe the problem is that the shared library is built for x86_64 but your hardware uses aarch64.   If you can build epics base on that environment or download libca.so and libCom.so for that architecture, say from https://jenkins.aps.anl.gov/view/EPICS%20Base/, though I do not know if that has aarch64 automatically built.

Once you find those two files for your architecture, you can put them anywhere on your system (in the same folder) and then set the environmental variable PYEPICS_LIBCA to be the full path to that libca.so.

**Comment by elderwann** [comment]
Thank you, but how can I download libca.so or libCom.so from //jenkins.aps , I tried but nothing works.

**Comment by elderwann** [comment]
Is a solution to copy libca.so from a raspberry pyepics version and paste it on the odroid. From odroid terminal do export PYEPICS_LIBCA=/usr/local/Folder_where_I_paste_the_libca.so_file  ?  Thank you very much.  Pyepics working correctly on raspberry..

**Comment by newville** [comment]
@elderwann I am not sure if (or where) pre-built versions of libca.so and libCom.so are readily available.   If you have the gcc compiler suite installed on your system, you might be able to build that yourself:  Epics base is not too difficult to build for someone with some familiarity with either EPICS development or gcc skills.  The configuration process is a bit "by hand" and "per architecture", but documented, and the build itself is generally smooth.

**Comment by elderwann** [comment]
Why when I do  :   export PYEPICS_LIBCA=/usr/local/lib/python3.8/dist_packages/epics/clibs/linuxarm64
and after, from python3 :  epics.ca.find_libca()   
it returns : '/usr/local/lib/python3.8/dist-packages/epics/clibs/linuxarm/libca.so'    
and not with linuxarm64/libca.so  ?

**Comment by elderwann** [comment]
Yes, after re install pyepics the linuxarm64 is now existing.. and export command works.

**Comment by newville** [comment]
Did you find or build the appropriate libraries? If so, and they work, can you share them?

**Comment by elderwann** [comment]
I didn't find the appropriate libraries, I really don't know how and / where to find it. I'm not comfortable with building libraries. Maybe I will take a part of night to try to do...  Many thanks for your help.

**Comment by elderwann** [comment]
regarding to these new informations, when I run 
export EPICS_HOST_ARCH=`/usr/local/epics/base-3.16.2/startup/EpicsHostArch`
export EPICS_HOST_ARCH=$(/usr/local/epics/base-3.16.2/startup/EpicsHostArch)
it returned :  
src/tools/EpicsHostArch.pl: Architecture 'aarch64-linux-gnu-thread-multi' not recognized

What does that mean ? the impossibility to use pyepics on that odroid ?

**Comment by newville** [comment]
I am concerned that you have not answered a direct and specific question that I have now asked you twice.  If you want further help,  you will need to answer my questions.

**Comment by elderwann** [comment]
Hi, I tried to point PYEPICS_LIBCA to linux_x86_64/libca.so . 
Difficulty was I have no linux_x86_64 folder in the compile EPICS repertory.
While I write :  
>>> import epics
>>> epics.ca.find_libca()        it returns again 
'/usr/local/lib/python3.9/dist-packages/epics/clibs/linux64/libca.so'

so I tried to do (in python terminal or not ?) 
export PYEPICS_LIBCA=/usr/local/lib/python3.9/dist-packages/epics/clibs/linux_x86_64/libca.so

In where "/usr/local/lib/python3.9/dist-packages" is from the compile epics repertory or the epics base ?

I read some docs all the day in order to better understand how to, but at time nothing seems to be good. If you have some advices. Thanks.

**Comment by elderwann** [comment]
So I if well understand the problem, I need to add the libca.so and libCom.so file to the linux_x86_64 folder. I have to build these libraries from epics base (base-3.16.2  or  base-7.0.3.1  ?) and compile them, is that correct ?
I currently never did compilation.
After that, I will have to export PYEPICS_LIBCA in order to reaffect these lib to epics, correct ?

**Comment by elderwann** [comment]
Hello, So I finally succeed in using libca.so and libCom.so from linux-x86_64 libraries ( https://jenkins.aps.anl.gov/view/EPICS%207/job/epics-7.0/OS=linux64/ws/lib/linux-x86_64/ ), but the result stay the same while starting pv=epics.PV('VARIABLE').

Result :


>>> import epics
>>> pv=epics.PV('AR')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/epics/ca.py", line 376, in initialize_libca
    libca = load_dll(find_libca())
  File "/usr/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.9/dist-packages/epics/clibs/linux64/libca.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/epics/ca.py", line 376, in initialize_libca
    libca = load_dll(find_libca())
  File "/usr/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.9/dist-packages/epics/clibs/linux64/libca.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/epics/pv.py", line 246, in __init__
    if ca.current_context() is None:
  File "/usr/local/lib/python3.9/dist-packages/epics/ca.py", line 546, in wrapper
    initialize_libca()
  File "/usr/local/lib/python3.9/dist-packages/epics/ca.py", line 378, in initialize_libca
    raise ChannelAccessException('loading Epics CA DLL failed: ' + str(exc))
epics.ca.ChannelAccessException: loading Epics CA DLL failed: /usr/local/lib/python3.9/dist-packages/epics/clibs/linux64/libca.so: cannot open shared object file: No such file or directory

**Comment by elderwann** [comment]
Hello, Thank-you for all, I will retry pyepics installation, and currently searching libca for aarch64. 
I'll post new comment if good news..

**Comment by elderwann** [comment]
Just to complete and finish :  

Do you interpret that to mean something other than that file does not exist?  

The fact is into the folder there are libca.so and libCom.so files. So files exists.
