### ISSUE TITLE
Application using pyepics may crash after epics.ca.clear_cache()

### ISSUE THREAD

**Issue by hanak** [pyepics/pyepics#247]
This issue requires use of `epics.ca*` with auto-monitoring enabled and `epics.ca.clear_cache()` at the same time with a little bit of timing "luck". If conditions are right, the application may crash after using `epics.ca.clear_cache()` if it used `epics.ca*()` (e.g. `epics.caget()`) beforehand.

GDB stack trace:

![image](https://github.com/pyepics/pyepics/assets/178428/bd5fe2a2-698f-4792-a489-3bae40c93aa3)

**Comment by hanak** [comment]
**Analysis**

When `ca.clear_cache()` is called, it will use `clear_channel()` to disconnect all channels from EPICS. This will clear any subscription. Yet, if any instance of `PV` refrencing chid closed `clear_channel()` attempts to disconnect, it may or may not call `ca_clear_subscription()`. If it does, SIGSEGV will likely occur because EPICS monitor references the channel internally and the channel (incl. its internal structures) has been destroyed already by `ca_clear_channel()`.

If the application uses the class `PV` directly, it can use `PV.disconnect()` (or `PV.auto_monitor = False`) all prior calling `ca.clear_cache()`. This will remove the PV from `pv._PVcache_`. However, if the application uses `epics.ca*()`, the instances of `PV` stay in `pv._PVcache_` until `ca.clear_cache()` releases them. Later, GC will destroy them and this will call `PV.disconnect()` leading to SIGSEGV described above.

**Potential Solution**

`ca.clear_cache()` should disable auto_monitors of PVs listed in `pv._PVcache_` prior calling `clear_channel()`.

**Comment by newville** [comment]
@hanak Thanks! I agree that `ca.clear_cache()` should probably be safer, and with the analysis.  I would say that if it works to do `PV.disconnect()` (or perhaps `del pv` if that seems cleaner, it is basically the same thing) works from `epics.ca.clear_cache()`, then yes to a PR:  if that works, let's fix that.   So: thanks very much and yes, please to a PR.
