### ISSUE TITLE
wrong int format conversion character in pv.pv line 877

### ISSUE THREAD

**Issue by epanepucci** [pyepics/pyepics#251]
hello,

in file epics/pv.pv on line 877:
`    fmt = '{val:i}'
`
"i" is not a valid format identifier; "d" should be used instead.

Cheers
Zac

**Comment by newville** [comment]
@epanepucci Thanks! I'm sort of surprised that this did not get flagged earlier - we must not be tickling this in any tests. I fixed it in the Github master branch (0b33db782dde77d89ee847bee4e6fc314bc3c30b).

FWIW,  `x = "%i" % val` like formatting of ints does still work.  This is in use in many parts of the code, but I'll replace all of these with "%d" or move to more modern formatting.

**Comment by epanepucci** [comment]
Hi, I've successfully used a tool in the past to update string formatting code to f-strings.
Here is the link: https://github.com/ikamensh/flynt

**Comment by newville** [comment]
@epanepucci Thanks - I guess that converting much of pyepics to use f-strings (at least where easy to do so) would be a fine thing to keep the code up-to-date.   I'm not sure that I'm going to do that soon, but it would be a fine contribution from someone with the time and inclination.
