### ISSUE TITLE
Apple Silicon ARM support for libca.so

### ISSUE THREAD

**Issue by prichards-wmko** [pyepics/pyepics#252]
I am running Ubuntu on an Apple Macbook Pro laptop with an M2 (ARM64) processor (in Parallels).

When importing the pyepics library and instantiating a PV object, the _find_lib() method finds the linux64/libca.so which is compiled for Intel and it fails to load.  (For some reason the error is wrong; the file is exactly where it says.)

OSError: /usr/local/anaconda/lib/python3.11/site-packages/epics/clibs/linux64/libca.so: cannot open shared object file: No such file or directory

I see there is a libca.so provided for ARM under linuxarm, but it is a 32 bit version.  It cannot be loaded on Apple Silicon.

$ file /usr/local/anaconda/lib/python3.11/site-packages/epics/clibs/linuxarm/libca.so 
libca.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=80e383a5d2390eeaa52ccd9a7e5a0380ddd4e16b, with debug_info, not stripped

My compile of EPICS yielded a libca.so that looks like this:

$ file /usr/local/epics/default/base/lib/linux-arm/libca.so.3.15.9
/usr/local/epics/default/base/lib/linux-arm/libca.so.3.15.9: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=c816bd02c41bc17a9dc9dc54c985ab831b6d386b, not stripped

For now I can live with defining PYEPICS_LIBCA before importing epics.  This works well enough for now.

Native support for Apple Silicon ARM would be greatly appreciated.

**Comment by newville** [comment]
@prichards-wmko Sorry for the trouble.  It does work for me (M1 macOS), but I guess I must be testing only with Anaconda Python built for x86_64 macOS because of other libraries.   Yeah, linux-arm will almost certainly not work. 

I guess we'll have to build and add the shared libs for darwin-aarch64 with base-7.0.7.  FWIW,  I have an M1 macOS system, but it looks like that would be compatible with M2.

**Comment by newville** [comment]
@prichards-wmko I think this is resolved.
