### ISSUE TITLE
PV callback using auto_monitor to include limit severities

### ISSUE THREAD

**Issue by fonty422** [pyepics/pyepics#257]
I'm looking for a way to monitor a PV and include the following attributes:
VAL, STAT, SEVR, HIHI, HIGH, LOW, LOLO, EGU, PREC, HHSV, HSV, LSV, and LLSV.

I can easily create a PV object with a callback that includes most of these values:
`PV("SOME_NAME:MONITOR", auto_monitor=( dbr.DBE_VALUE | dbr.DBE_PROPERTY ), callback=handle_callback)`

This does as we want and we correctly trigger the callback on any of the above except we never seem to get the limit severities. It seems as though we need to connect to those individually.

At the moment, the best option seems to be to connect to the original PV, then use the attributes that are not None to then create an Alarm object with the attrs field set to these missing attributes. But I think that will be equivalent to creating 4 additional PV objects connecting to SOME_NAME:MONITOR.HHSV to SOME_NAME:MONITOR.LLSV, which is extra unwanted overhead.

Is there a solution to this, or have I misunderstood that the limit severities are not part of PV in the same way that DESC is also not part of the PV?

**Comment by fonty422** [comment]
Just in addition to that, if it set up the PV as above and but include the dbr.DBE_ALARM option then I modify the and of HHSV, HSV, LSV, or LLSV, the callback does indeed trigger and I get all the values come through except the limit severities, so it is aware of an alarm change, but we just don't seem to get access to the values for these fields/attributes.

**Comment by newville** [comment]
@fonty422 right, I think it is correct that alarm values are separate. 

I don't see a definitive list of which fields generate DBE_PROPERTY events other than "enum strings, display limits, alarm limits, units, precision etc".  Perhaps it depends on record type.

**Comment by fonty422** [comment]
Same, I simply can't find where the mapping from EPICS field (HIHI, STAT, SEVR etc) to pyepics (upper_alarm_limit, status, severity) is made. If we could find this mapping, then we could just add it as an option in the relevant places.
But trying a few things as a guess like upper_alarm_severity simply returns the value of the PV and has no relevance to the limits at all. Where is the mapping done? Is that on the ca side of things, or still somewhere in pyepics?
If the record has that field present (which is does and I can specifically call it with `PV("SOME_NAME:MONITOR.HHSV").get()`, surely we can have it so this field is included in the channel connection?

**Comment by fonty422** [comment]
It seems it's on the [epics side](https://github.com/epics-base/epics-base/blob/7.0/modules/ca/src/client/db_access.h#L411).
This is where the strange names for HIHI=>upper_alarm_limit come from.

The question is whether it's reasonable to modify this. I'm very unfamiliar with C, so I assume any modification in here is actually a little crazy, maybe needs compiling etc.

**Comment by newville** [comment]
@fonty422 I think we can close this as "not fixable by us"

**Comment by fonty422** [comment]
Agreed. Our workaround is clunky and creates a little more overhead, but it's functional.
