### ISSUE TITLE
Please add the dbr.DBE_PROPERTIES to the documentation

### ISSUE THREAD

**Issue by fonty422** [pyepics/pyepics#258]
Hi team,
Just wondering whether you can add some detail about the dbr.DBE_PROPERTIES to the documentation? We found the option by accident while trying to figure out how to get a regular callback to trigger on alarm limit changes (not values that go cross limits, but actual changes to the limit).
I'm sure there are more than a few people who would find this option useful for subscribing callbacks to not just values, but also changes to limits.

**Comment by newville** [comment]
@fonty422 Thanks -- that's a great suggestion. I agree that this option should be better known and explained.  I think  is missing mostly due to my own lack of familiarity with this option with the CA library.  ;) 

If you have any more concrete suggestions or examples for the doc, please let me know or feel free to make a Pull Request.

**Comment by fonty422** [comment]
Thanks @newville.
If I were cleaver enough to understand the CA library myself and knew how to do a pull request I would happily contribute, but that's a bit out of my wheelhouse and would worry me that I would break something.

I think it's a little known option and I'm sure if it were more visible it would be used more frequently. I can see the value of choosing _how_ to trigger a callback.

My suggestion is to modify [this section](https://pyepics.github.io/pyepics/pv.html#automatic-monitoring-of-a-pv) to explain what masks do - it's not entirely clear that these are methods to modify the default behaviour of a callback which triggers on a value change and that you can specify how they are triggered. Perhaps we offer a table for the attributes showing what will be returned in a callback if each of the options are set?

In our case, we need to be notified when a value changes as well as if the limits on the record are modified so we can adjust some other software, but we don't want to set up individual PV objects to monitor every possible option (considering that some records don't have all of these attributes set), plus it adds a lot of overhead to create a direct connection to a specific attribute.

Here's a snippet of our code:

```python
def handle_update(pvname, value, status, severity, timestamp, upper_alarm_limit=None, upper_warning_limit=None,
                  lower_warning_limit=None, lower_alarm_limit=None):
    if upper_alarm_limit is not None:
        if isnan(upper_alarm_limit):
            # case to handle the event where pyepics returns a nan for a
            # meaningless limit (where there is a real value set for the limit, but severity for this limit is NO_ALARM)
        else:
            # Do something with the update
pv = PV("XXX:YYY", callback=handle_update, form="ctrl", auto_monitor=(dbr.DBE_VALUE | dbr.DBE_PROPERTY))
```

When we modify the HIHI limit on the PV it is reflected in the callback.
Without this whenever the callback triggers the upper_alarm_limit value remains unchanged even if it has been modified in the mean time.

**Comment by newville** [comment]
There is now an example in the docs using `dbr.DBE_PROPERTY`.

**Comment by fonty422** [comment]
Thanks! That's a nice, clear, and concise example.

**Comment by newville** [comment]
@fonty422 Thanks...  the docs do seem like they could use some attention. It might be time (or, based on some things I've seen recently, past time) to give a bit more of a how-to user guide and some example scripts.
