### ISSUE TITLE
Script hangs at the exit when using pcaspy + pyepics

### ISSUE THREAD

**Issue by hinxx** [pyepics/pyepics#259]
I'm using this simple script to demonstrate about 30 second hang after the `server_thread joined!` is printed.
This is on Linux using latest versions of pcaspy and pyepics under python 3.10.

```
import threading
from pcaspy import SimpleServer, Driver
import epics
import time
from pcaspy.tools import ServerThread


class ClientThread(threading.Thread):
    def __init__(self):
        super(ClientThread, self).__init__(name='ca client')
        self.stop = False
        self._data = None
        self.pv = epics.PV('scan:running', callback=self.chgcb, connection_callback=self.concb, auto_monitor=True)

    def concb(self, **args):
        print('PV concb called')

    def chgcb(self, **args):
        print('PV chgcb called')
        self._data = args
    
    def run(self):
        while not self.stop:
            time.sleep(1)
            if self._data:
                print('value', self._data['value'])

        self.pv.clear_auto_monitor()
        self.pv.disconnect()
        
        print('CA client thread finished!')

prefix = 'scan:'
pvdb = {
    'running' : { 'type' : 'enum', 'enums': ['No', 'Yes'] },
}

class myDriver(Driver):
    def __init__(self):
        super(myDriver, self).__init__()

        self.setParam('running', 0)
        self.updatePVs()


if __name__ == '__main__':
    server = SimpleServer()
    server.createPV(prefix, pvdb)
    driver = myDriver()
    server_thread = ServerThread(server)
    server_thread.start()
    
    client_thread = ClientThread()
    client_thread.start()

    print('sleeping 10s..')
    time.sleep(10)
    print('done sleeping!')
    server_thread.stop()

    client_thread.stop = True
    client_thread.join()
    print('client_thread joined!')

    server_thread.join()
    print('server_thread joined!')

    # ~30 s HANG! then exit
```

Execution:

```
$ time python thr1.py 
cas warning: Configured TCP port was unavailable.
cas warning: Using dynamically assigned TCP port 36211,
cas warning: but now two or more servers share the same UDP port.
cas warning: Depending on your IP kernel this server may not be
cas warning: reachable with UDP unicast (a host's IP in EPICS_CA_ADDR_LIST)
sleeping 10s..
PV concb called
PV chgcb called
value 0
value 0
PV chgcb called
value 1
PV chgcb called
value 0
PV chgcb called
value 1
value 1
value 1
value 1
value 1
done sleeping!
value 1
CA client thread finished!
client_thread joined!
server_thread joined!


^C^C

^C^C

real	0m40,333s
user	0m0,658s
sys	0m0,558s
```

Sometimes the hang is followed by a segfault, other times it seems to exit cleanly. It is hard to say what is going on during that wait time. If I press `Ctrl+C` the script does not finish immediately during the hang.

Any pointers on how to debug this situation?

When I replace the pyepics with CaChannel and try I do not observe the hanging at the end of script. In my actual use case a more elaborate 3rd party module is using pyepics and I can't simply replace pyepics in it with CaChannel.

If I use separate scripts for server / client parts there is no issues.

**Comment by hinxx** [comment]
Here is the script with CaChannel for reference, and the execution.

```
import threading
from pcaspy import SimpleServer, Driver
import time
from pcaspy.tools import ServerThread
import epicsPV


class ClientThread(threading.Thread):
    def __init__(self):
        super(ClientThread, self).__init__(name='ca client')
        self.stop = False
        self._data = None
        self.pv = epicsPV.epicsPV('scan:running', wait=True)
        self.pv.setMonitor()

    def concb(self, **args):
        print('PV concb called')

    def chgcb(self, **args):
        print('PV chgcb called')
        self._data = args
    
    def run(self):
        while not self.stop:
            time.sleep(1)
            if self.pv.checkMonitor():
                self._data = self.pv.getValue()
                print('value', self._data)

        print('CA client thread finished!')

prefix = 'scan:'
pvdb = {
    'running' : { 'type' : 'enum', 'enums': ['No', 'Yes'] },
}

class myDriver(Driver):
    def __init__(self):
        super(myDriver, self).__init__()

        self.setParam('running', 0)
        self.updatePVs()


if __name__ == '__main__':
    server = SimpleServer()
    server.createPV(prefix, pvdb)
    driver = myDriver()
    server_thread = ServerThread(server)
    server_thread.start()
    
    t1 = ClientThread()
    t1.start()

    print('sleeping 10s..')
    time.sleep(10)
    print('done sleeping!')
    server_thread.stop()

    t1.stop = True
    t1.join()
    print('t1 joined!')

    server_thread.join()
    print('server_thread joined!')

    # NO HANG
    
```

```
$ time python thr5.py 
cas warning: Configured TCP port was unavailable.
cas warning: Using dynamically assigned TCP port 40007,
cas warning: but now two or more servers share the same UDP port.
cas warning: Depending on your IP kernel this server may not be
cas warning: reachable with UDP unicast (a host's IP in EPICS_CA_ADDR_LIST)
sleeping 10s..
value 0
value 1
value 0
value 1
done sleeping!
CA client thread finished!
t1 joined!
server_thread joined!
CA.Client.Exception...............................................
    Warning: "Virtual circuit disconnect"
    Context: "bd-srv07.cslab.esss.lu.se:40007"
    Source File: ../cac.cpp line 1225
    Current Time: Tue Apr 23 2024 10:01:41.744907037
..................................................................

real	0m10,220s
user	0m0,546s
sys	0m0,590s

```

**Comment by newville** [comment]
@hinxx Does this use `pyepics`?   I don't know what your `import epicsPV` does.  I don't know much about `pcaspy`, but it seems like that the problem is happening when the server disconnects.

**Comment by hinxx** [comment]
The code example in second comment does not use `pyepics`, but `CaChannel` instead (`epicsPV` is part of `CaChannel`). I've included it to show that when the same `pcaspy` code is used with `CaChannel` instead of `pyepics`, the script does not hang for 30 seconds at the exit. Therefore I'm guessing that the issue I'm seeing is maybe related to the `pyepics`.

Let me reiterate the problem: when the script in first comment is ran it takes additional 30 seconds to exit after the script is done and prints `server_thread joined!`. You can see that the script sleeps 10 seconds but the time printed after the execution is 40 seconds. There are no apparent errors printed, but just hangs there until 30 seconds have passed, and I can't use Ctrl+c to stop execution during that time.

**Comment by newville** [comment]
@hinxx Again, I don't know much about pcaspy and have no recollection of any details of CaChannel.   

Does this happen if you use epics.ca.CAThread (https://pyepics.github.io/pyepics/ca.html#cathread-class) instead of creating pyepics PVs in a plain thread?

**Comment by hinxx** [comment]
I've done some debugging and came to the root cause of the problem ; where the 30 seconds delay comes from.
It is from epics-base:

https://github.com/epics-base/epics-base/blob/cb1571783b4793cb9c545e5736659ee5ed7d03bb/modules/ca/src/client/tcpiiu.cpp#L205

After adding several printf() around the relevant code there I can confirm that the call to `ca_context_destroy()` in CA clients causes that code to wait 30 seconds for something to happen.

Also, the issue is not pyepics specific as I could reproduce the same with an example CA server C++ code and example CA client code.

**Comment by newville** [comment]
@hinxx hmm, that seems strange.  For sure, that delay does not always happen on exit of a script.  That is, I think that closing a context taking 30 seconds should still be viewed as a problem.  Why is that happening? 

What version of CA lib is being used?

**Comment by hinxx** [comment]
The delay happens only if the CA server and CA client are used together AND `ca_context_destroy();` is used to 'cleanly' shutdown the client as far as I observed.
I agree that closing the context should not take 30 seconds. Judging from the comments in the EPICS base code this could rarely happen but I do not see any clear arguments why it happens and why does that code wait for an arbitrary amount of time (30 sec) before continuing to close the context and shutdown the CA client threads. As I wrote in that epics-base ticket, if I changed that timeout value to 5 seconds instead of 30, the delay is now only 5 seconds long without any noticeable errors or problems reported by the rest of the code..

**Comment by newville** [comment]
@hinxx Hmm, yeah that's kind of odd.  But, maybe another reason to prefer multiple processes to multiple threads within one process for CA.   Creating a CA PV to communicate data to another thread seems way overkill -- there are lots of ways to share data between threads.  ;).

**Comment by hinxx** [comment]
My use case is creating an IOC (ie. a high level IOC or a manager IOC) that will communicate with other IOCs (ie. ones that talk to some hardware and there are many of them). For this the purpose the manager IOC needs to do CA client type of access; ie.  local CA client. But, since it is also an IOC (using pcaspy), it would also serve its own set of PVs to remote CA clients.

It felt natural to expect that the same process could cope with client side of the same process talking to the server side over CA; I wanted to treat this local CA client just as any other remote CA clients that my CA server would handle. In the end I want to report state or allow control of the server PVs from the local CA client as well as from any remote CA clients. Doing it this was would simplify dealing with shared state.

It is true that I wanted to use CA as an interface for shared data between the client and server part directly over CA. Seems that I was wrong to expect this would work as anticipated, and too lazy to implement something that does not do CA for such needs.. back to the drawing board.

**Comment by newville** [comment]
@hinxx Thanks - I understand the use case better.   
I should admit that 

I should admit that I just never really use pcaspy or CAS.  With multiple softIOCs - I use 4 or 5 (depending on detector configuration)  that are essentially always running just for my one beamline.  

With that, adding a simple database of PV names to a softIOC is really simple -- they don't have to do anything, but the softIOC holds and manages the lifecycle of the PVs: it's the "server" of the PVs but not necessarily the content.

With that, you can write any program (in any language) to access the PVs. So a Python script can easily read from other IOCs, do some calculation/manipulation, and then write to variables in another IOC.   The Python script can be restarted, moved, etc and PVs don't go away or disconnect.

**Comment by hinxx** [comment]
I just want to add my latest findings on how I can solve the problem of the script hanging for 30 seconds at exit.

It turns out that I need to explicitly delete the `pcaspy` server, driver and thread objects in order to force pcas server to be destroyed (C++ destructor called) which is not otherwise destroyed due to reference count > 0 (and is left to the GC instead that kicks in too late). As soon as CA server is gone the CA channels get disconnected and destroyed right away (stopping the TCP send/recv threads).

For completeness here is the modified script from initial post:

```
import threading
from pcaspy import SimpleServer, Driver
import epics
import time
from pcaspy.tools import ServerThread


class ClientThread(threading.Thread):
    def __init__(self):
        super(ClientThread, self).__init__(name='ca client')
        self.stop = False
        self._data = None
        self.pv = epics.PV('scan:running', callback=self.chgcb, connection_callback=self.concb, auto_monitor=True)

    def concb(self, **args):
        print('PV concb called')

    def chgcb(self, **args):
        print('PV chgcb called')
        self._data = args
    
    def run(self):
        while not self.stop:
            time.sleep(1)
            if self._data:
                print('value', self._data['value'])

        self.pv.clear_auto_monitor()
        self.pv.disconnect()
        
        print('CA client thread finished!')

prefix = 'scan:'
pvdb = {
    'running' : { 'type' : 'enum', 'enums': ['No', 'Yes'] },
}

class myDriver(Driver):
    def __init__(self):
        super(myDriver, self).__init__()

        self.setParam('running', 0)
        self.updatePVs()


if __name__ == '__main__':
    server = SimpleServer()
    server.createPV(prefix, pvdb)
    driver = myDriver()
    server_thread = ServerThread(server)
    server_thread.start()
    
    client_thread = ClientThread()
    client_thread.start()

    print('sleeping 10s..')
    time.sleep(10)
    print('done sleeping!')
    server_thread.stop()

    client_thread.stop = True
    client_thread.join()
    print('client_thread joined!')

    server_thread.join()
    print('server_thread joined!')

    del driver
    del server
    del server_thread

    # NO HANG !

```
