### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mrakitin** [pyepics/pyepics#260]
Hello @newville! Is there a plan to release a new version soon? I am interested in this particular fix: https://github.com/pyepics/pyepics/commit/0b33db782dde77d89ee847bee4e6fc314bc3c30b, which was implemented in December of 2023, while the latest release is from September 2023. Thanks!

**Comment by newville** [comment]
@mrakitin Ah, good point.  I suppose I should address #258 first, and maybe add binaries for Silicon Arm (#252).  

Is it OK with you to aim for a release early next week, or "by June 1"?

**Comment by mrakitin** [comment]
Sounds great, Matt, no rush on our end!

**Comment by newville** [comment]
@mrakitin A little later than hoped, but 3.5.3 is now released. Let me know if you have any trouble.
