### ISSUE TITLE
Printing Alarm objects crashes

### ISSUE THREAD

**Issue by NichtJens** [pyepics/pyepics#262]
Printing an Alarm object does not work since its `__repr__` references `pv.name` instead of `pv.pvname`.

PR for the (tiny!) fix here: https://github.com/pyepics/pyepics/pull/261

(I am only also opening an issue because the PR template suggested it. Hope that's as it should be :))

**Comment by newville** [comment]
Good catch! Thanks.

**Comment by NichtJens** [comment]
Ah, you merged it already. Great! Then I'll close this :)
