### ISSUE TITLE
Support setup.py develop

### ISSUE THREAD

**Issue by klauer** [pyepics/pyepics#38]
Since only the top-level path which contains `setup.py` is added to the search path during a source install, and the library source directory is named `lib`, `import epics` fails:

```bash
$ python setup.py develop
$ ipython
```

```python
In [1]: import epics
ImportError: No module named epics

In [2]: import lib

In [3]: lib.__file__
Out[3]: '/Users/klauer/Repos/pyepics/lib/__init__.pyc'
```

Easy solution: rename `lib` to `epics`.

**Comment by newville** [comment]
@klauer agreed.  That would be a good idea.
