### ISSUE TITLE
Segfault in attach_context for new threads

### ISSUE THREAD

**Issue by mccullerlp** [pyepics/pyepics#51]
I started getting this in linux using a pretty heavily multithreaded program. I don't know when it started happening, but it occures in 3.2.4. 

running 

```
import epics
import threading
epics.ca.use_initial_context()
t = threading.Thread(target = lambda : epics.ca.use_initial_context())
t.start()
```

causes a segfault.

I determined the cause was from the return value of current_context() as stored in initial_context isn't properly being interpreted as a pointer in ca_attach_context.

The fix is to include 

libca.ca_attach_context.argtypes  = [ctypes.c_void_p]

along with all of the other ctypes annotations in initialize_libca. This is also likely related to the segfault mentioned in issue #37

**Comment by newville** [comment]
@mccullerlp  Thanks for another great suggestion.   I'm not sure this will address #37, but it might help.
Will fix.

**Comment by newville** [comment]
@mccullerlp   addresses hopefully!) #52.   Thanks!!

**Comment by klauer** [comment]
#52 appears to have fixed #37 and this issue. The darwin check in `CAThread` appears to be unnecessary now - I'll open a PR for that soon.

Closing for now.

**Comment by newville** [comment]
@klauer Thanks!   I'd like be able to release 3.2.5 soon -- it's been a long time and there have been many improvements (mostly from you and @mccullerlp) in the past year. 

Any objections to  tagging the current version as 3.2.5 and pushing it out?

**Comment by klauer** [comment]
@newville no problem. Give me a couple days, I'd like to get some minor fixes and a bit more test coverage in before the tag.
