### ISSUE TITLE
camonitor does not react on change when data array is too big

### ISSUE THREAD

**Issue by piuupiuupiuu** [pyepics/pyepics#84]
Hi,
I am running a server for a camera which can be triggered by sending a `pv1.put(frames)` and is sending data via a second pv using `pv2.get()`. This is working without any problem even with long numpy arrays (currently 493*659 pixel) if the environmental variable EPICS_CA_MAX_ARRAY_BYTES is set accordingly high.
It would be nice to monitor the pv2 to just send a `pv1.put(frames)` and get the picture with the shortest delay, but I tried with a few array sizes and it seems like `camonitor` just doesn't work if the array size exceeds some value between 57600 and 78400. There is no error message and no crash of the programm, it just doesn't react on value changes of pv2.
I hope someone can reproduce this.
Thanks and best regards
p

**Comment by newville** [comment]
@piuupiuupiuu I think you want to set `auto_monitor=True` when creating the PV.  By default,  `auto_monitor=None`, and the internal monitors will be set up only when the `count` is less than `ca.AUTOMONITOR_MAXLENGTH`, which has a default value of 65536.  That is, pyepics intentionally does not automatically monitor array PVs that are "too large".

You could also increase `ca.AUTOMONITOR_MAXLENGTH`, which might be preferred for programs connecting to lots of array PVs.

For more, see http://pyepics.github.io/pyepics/pv.html#automatic-monitoring-of-a-pv

Also note that many programs/iocs generating large arrays for images like anything from areaDetector also have an "image counter".   It's common to monitor and react to *that*, say setting a "need to process image" flag with some other code reacting to that to do "pv.get()" on the image array data.  The advantage with that approach is that allows you to skip frames if the mage handling/viewing/processing is ever slower than the data rate.

I think this is answered and will close this Issue.

**Comment by piuupiuupiuu** [comment]
`auto_monitor=True` is already the default value when using `camonitor(pvname)`.

Nevertheless setting `ca.AUTOMONITOR_MAXLENGTH` is working.

Thank you!
