### ISSUE TITLE
pyepics 3.2.7

### ISSUE THREAD

**Issue by hhslepicka** [pyepics/pyepics#86]
Hi @newville, I am very interested on the callbacks for write_access. Do you plan to cut a release of PyEpics soon that will include those changes on master?

Thanks!

**Comment by newville** [comment]
@hhslepicka there is at least one incompletely resolved ( #83, though I think @rokvintar has this solved)  I think #83 and #85 and both merge-able.   

My schedule is pretty full the next couple weeks.  Would it be reasonable to aim for September 1?

**Comment by hhslepicka** [comment]
Thank you @newville! September 1st sounds reasonable. In the worst case we can source install as I did for my tests. Feel free to keep this issue open or to close it!
Cheers!

**Comment by hhslepicka** [comment]
Hi @newville! Just following up to check if we can keep that target of September 1st.
Thank you again!

**Comment by newville** [comment]
@hhslepicka I think this is now all fixed (basically, I added `as_numpy=False` to the `get()` calls as otherwise it was returning numpy string ndarrays instead of lists of strings).

**Comment by newville** [comment]
OK, 3.2.7 is now released.

**Comment by hhslepicka** [comment]
Thank you @newville !
